Repository Azure/azure-sdk-for-android, pull requests merged in 2020-11, with the labels that each got.

#443 Sync eng/common directory with azure-sdk-tools for PR 1160
  eng/common/scripts/Delete-RemoteBranches.ps1
  eng/common/scripts/git-branch-push.ps1
Labels: Central-EngSys, EngSys

#446 Sync eng/common directory with azure-sdk-tools for PR 1167
  eng/common/scripts/git-branch-push.ps1
Labels: Central-EngSys, EngSys

#447 Sync eng/common directory with azure-sdk-tools for PR 1175
  eng/common/TestResources/New-TestResources.ps1
Labels: Central-EngSys, EngSys

#449 Sync eng/common directory with azure-sdk-tools for PR 1163
  eng/common/TestResources/New-TestResources.ps1
  eng/common/TestResources/New-TestResources.ps1.md
  eng/common/TestResources/Remove-TestResources.ps1
  eng/common/TestResources/deploy-test-resources.yml
Labels: Central-EngSys, EngSys

#451 Sync eng/common directory with azure-sdk-tools for PR 1178
  eng/common/README.md
Labels: Central-EngSys, EngSys

#452 Sync eng/common directory with azure-sdk-tools for PR 1185
  eng/common/README.md
Labels: Central-EngSys, EngSys

#454 Sync eng/common directory with azure-sdk-tools for PR 1188
  eng/common/TestResources/New-TestResources.ps1
Labels: Central-EngSys, EngSys

#455 Sync eng/common directory with azure-sdk-tools for PR 1190
  eng/common/TestResources/New-TestResources.ps1
Labels: Central-EngSys, EngSys

#448 Sync eng/common directory with azure-sdk-tools for PR 1170
  eng/common/scripts/Verify-Links.ps1
  eng/common/scripts/get-markdown-files-from-changed-files.ps1
Labels: Central-EngSys, EngSys

#445 Sync eng/common directory with azure-sdk-tools for PR 1161
  eng/common/scripts/Get-PullRequestCreator.ps1
  eng/common/scripts/Invoke-DevOpsAPI.ps1
  eng/common/scripts/Invoke-GitHubAPI.ps1
  eng/common/scripts/Queue-Pipeline.ps1
  eng/common/scripts/Submit-PullRequest.ps1
Labels: Central-EngSys, EngSys

#456 Sync eng/common directory with azure-sdk-tools for PR 1199
  eng/common/TestResources/deploy-test-resources.yml
Labels: Central-EngSys, EngSys

#457 Sync eng/common directory with azure-sdk-tools for PR 1202
  eng/common/TestResources/New-TestResources.ps1
Labels: Central-EngSys, EngSys

#453 Add more PR labels
  .github/CODEOWNERS
Labels: Central-EngSys, Client, EngSys

#458 Sync eng/common directory with azure-sdk-tools for PR 1153
  eng/common/scripts/ChangeLog-Operations.ps1
  eng/common/scripts/Package-Properties.ps1
  eng/common/scripts/SemVer.ps1
  eng/common/scripts/Update-ChangeLog.ps1
Labels: Central-EngSys, EngSys

#459 Sync eng/common directory with azure-sdk-tools for PR 1210
  eng/common/TestResources/New-TestResources.ps1
  eng/common/TestResources/New-TestResources.ps1.md
Labels: Central-EngSys, EngSys

#461 Sync eng/common directory with azure-sdk-tools for PR 1203
  eng/common/scripts/Add-IssueComment.ps1
  eng/common/scripts/Add-IssueLabels.ps1
  eng/common/scripts/Delete-RemoteBranches.ps1
  eng/common/scripts/Get-PullRequestCreator.ps1
  eng/common/scripts/Package-Properties.ps1
  eng/common/scripts/Queue-Pipeline.ps1
  eng/common/scripts/Submit-PullRequest.ps1
  eng/common/scripts/Update-ChangeLog.ps1
  eng/common/scripts/artifact-metadata-parsing.ps1
  eng/common/scripts/common.ps1
  eng/common/scripts/copy-docs-to-blobstorage.ps1
  eng/common/scripts/create-tags-and-git-release.ps1
  eng/common/scripts/update-docs-ci.ps1
  eng/common/scripts/update-docs-metadata.ps1
Labels: Central-EngSys, EngSys

#463 Sync eng/common directory with azure-sdk-tools for PR 1222
  eng/common/pipelines/templates/steps/docs-metadata-release.yml
Labels: Central-EngSys, EngSys

#464 Sync eng/common directory with azure-sdk-tools for PR 1219
  eng/common/docgeneration/Generate-DocIndex.ps1
  eng/common/docgeneration/assets/logo.svg
  eng/common/docgeneration/docfx.json
  eng/common/docgeneration/templates/matthews/partials/affix.tmpl.partial
  eng/common/docgeneration/templates/matthews/partials/class.header.tmpl.partial
  eng/common/docgeneration/templates/matthews/partials/class.tmpl.partial
  eng/common/docgeneration/templates/matthews/partials/enum.tmpl.partial
  eng/common/docgeneration/templates/matthews/partials/namespace.tmpl.partial
  eng/common/docgeneration/templates/matthews/styles/main.css
  eng/common/docgeneration/templates/matthews/styles/main.js
  eng/common/pipelines/templates/steps/docindex.yml
Labels: Central-EngSys, EngSys

#466 Sync eng/common directory with azure-sdk-tools for PR 1226
  eng/common/docgeneration/Generate-DocIndex.ps1
  eng/common/pipelines/templates/steps/docindex.yml
  eng/common/scripts/common.ps1
Labels: Central-EngSys, EngSys

#468 Sync eng/common directory with azure-sdk-tools for PR 1229
  eng/common/scripts/update-docs-metadata.ps1
Labels: Central-EngSys, EngSys

#462 Renaming
  sdk/communication/azure-communication-chat/README.md
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/AzureCommunicationChatServiceAsyncClient.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/AzureCommunicationChatServiceClient.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/implementation/AzureCommunicationChatServiceImpl.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/implementation/converters/SendChatMessageResultConverter.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/AddChatParticipantRequest.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/AddChatParticipantsRequest.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/AddChatThreadMembersRequest.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/ChatMessageReadReceipt.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/ChatMessageReadReceiptsCollection.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/ChatParticipant.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/ChatParticipantsCollection.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/ChatThread.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/ChatThreadInfo.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/CreateChatThreadRequest.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/Error.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/SendChatMessageResult.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/SendReadReceiptRequest.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/UpdateChatThreadRequest.java
  sdk/communication/azure-communication-chat/src/test/java/com/azure/android/communication/chat/chatClientTest.java
Labels: Communication

#465 Sync eng/common directory with azure-sdk-tools for PR 1220
  eng/common/pipelines/templates/steps/bypass-local-dns.yml
  eng/common/pipelines/templates/steps/verify-agent-os.yml
Labels: Central-EngSys, EngSys
