Repository Azure/azure-sdk-for-android, pull requests merged in 2020-10, with the labels that each got.

#357 Sync eng/common directory with azure-sdk-tools for PR 1031
  eng/common/TestResources/New-TestResources.ps1
  eng/common/TestResources/New-TestResources.ps1.md
  eng/common/TestResources/Remove-TestResources.ps1
  eng/common/TestResources/deploy-test-resources.yml
  eng/common/TestResources/setup-az-modules.yml
  eng/common/scripts/New-ReleaseAsset.ps1
Labels: Central-EngSys, EngSys

#376 Sync eng/common directory with azure-sdk-tools for PR 1052
  eng/common/pipelines/templates/steps/create-pull-request.yml
  eng/common/scripts/Add-Issue-Comment.ps1
  eng/common/scripts/Queue-Pipeline.ps1
  eng/common/scripts/git-branch-push.ps1
  eng/common/scripts/modules/ChangeLog-Operations.psm1
  eng/common/scripts/modules/Package-Properties.psm1
Labels: Central-EngSys, EngSys

#391 Sync eng/common directory with azure-sdk-tools for PR 1066
  eng/common/scripts/copy-docs-to-blobstorage.ps1
Labels: Central-EngSys, EngSys

#388 Sync eng/common directory with azure-sdk-tools for PR 1077
  eng/common/TestResources/New-TestResources.ps1
  eng/common/TestResources/New-TestResources.ps1.md
  eng/common/TestResources/README.md
Labels: Central-EngSys, EngSys

#395 [Communication SDK for Android]: Bump up version number for communication-common and communication-chat
  sdk/communication/azure-communication-chat/CHANGELOG.md
  sdk/communication/azure-communication-chat/build.gradle
  sdk/communication/azure-communication-common/CHANGELOG.md
  sdk/communication/azure-communication-common/build.gradle
Labels: Communication

#397 Sync eng/common directory with azure-sdk-tools for PR 1083
  eng/common/TestResources/New-TestResources.ps1
  eng/common/TestResources/README.md
Labels: Central-EngSys, EngSys

#401 Sync eng/common directory with azure-sdk-tools for PR 1081
  eng/common/README.md
  eng/common/scripts/Add-Issue-Comment.ps1
  eng/common/scripts/Add-IssueComment.ps1
  eng/common/scripts/Add-IssueLabels.ps1
  eng/common/scripts/Invoke-GitHubAPI.ps1
  eng/common/scripts/common.ps1
Labels: Central-EngSys, EngSys, auto-merge

#402 Sync eng/common directory with azure-sdk-tools for PR 1088
  eng/common/scripts/Delete-RemoteBranches.ps1
  eng/common/scripts/Invoke-GitHubAPI.ps1
Labels: Central-EngSys, EngSys, auto-merge

#406 Sync eng/common directory with azure-sdk-tools for PR 1091
  eng/common/pipelines/templates/steps/create-pull-request.yml
  eng/common/scripts/Add-IssueComment.ps1
  eng/common/scripts/Add-IssueLabels.ps1
  eng/common/scripts/Delete-RemoteBranches.ps1
  eng/common/scripts/Get-PullRequestCreator.ps1
  eng/common/scripts/Invoke-GitHubAPI.ps1
  eng/common/scripts/Submit-PullRequest.ps1
  eng/common/scripts/add-pullrequest-reviewers.ps1
Labels: Central-EngSys, EngSys, auto-merge

#404 Sync eng/common directory with azure-sdk-tools for PR 1062
  eng/common/scripts/Verify-Links.ps1
Labels: Central-EngSys, EngSys, auto-merge

#409 Sync eng/common directory with azure-sdk-tools for PR 1103
  eng/common/scripts/copy-docs-to-blobstorage.ps1
Labels: Central-EngSys, EngSys

#411 Sync eng/common directory with azure-sdk-tools for PR 1019
  eng/common/pipelines/templates/steps/verify-links.yml
Labels: Central-EngSys, EngSys

#412 Sync eng/common directory with azure-sdk-tools for PR 1106
  eng/common/scripts/copy-docs-to-blobstorage.ps1
Labels: Central-EngSys, EngSys

#408 Sync eng/common directory with azure-sdk-tools for PR 968
  eng/common/pipelines/templates/steps/publish-blobs.yml
  eng/common/scripts/Package-Properties.ps1
  eng/common/scripts/common.ps1
  eng/common/scripts/copy-docs-to-blobstorage.ps1
Labels: Central-EngSys, EngSys, auto-merge

#413 Sync eng/common directory with azure-sdk-tools for PR 1102
  eng/common/pipelines/templates/steps/create-pull-request.yml
  eng/common/pipelines/templates/steps/docs-metadata-release.yml
  eng/common/scripts/Invoke-GitHubAPI.ps1
  eng/common/scripts/Submit-PullRequest.ps1
Labels: Central-EngSys, EngSys

#415 Sync eng/common directory with azure-sdk-tools for PR 1128
  eng/common/scripts/modules/ChangeLog-Operations.psm1
Labels: Central-EngSys, EngSys

#417 Sync eng/common directory with azure-sdk-tools for PR 1104
  eng/common/pipelines/templates/steps/install-pipeline-generation.yml
  eng/common/pipelines/templates/steps/prepare-pipelines.yml
Labels: Central-EngSys, EngSys

#418 Sync eng/common directory with azure-sdk-tools for PR 1129
  eng/common/pipelines/templates/steps/prepare-pipelines.yml
Labels: Central-EngSys, EngSys

#419 Add prepare pipelines.
  eng/pipelines/prepare-pipelines.yml
Labels: Central-EngSys, EngSys

#421 Sync eng/common directory with azure-sdk-tools for PR 1132
  eng/common/pipelines/templates/steps/install-pipeline-generation.yml
  eng/common/pipelines/templates/steps/prepare-pipelines.yml
Labels: Central-EngSys, EngSys

#422 Sync eng/common directory with azure-sdk-tools for PR 1133
  eng/common/pipelines/templates/steps/prepare-pipelines.yml
Labels: Central-EngSys, EngSys

#420 Sync eng/common directory with azure-sdk-tools for PR 1127
  eng/common/TestResources/New-TestResources.ps1
Labels: Central-EngSys, EngSys

#423 Sync eng/common directory with azure-sdk-tools for PR 1131
  eng/common/pipelines/templates/steps/create-pull-request.yml
  eng/common/pipelines/templates/steps/docs-metadata-release.yml
  eng/common/scripts/Invoke-GitHubAPI.ps1
Labels: Central-EngSys, EngSys

#425 Sync eng/common directory with azure-sdk-tools for PR 1109
  eng/common/pipelines/templates/steps/docs-metadata-release.yml
Labels: Central-EngSys, EngSys

#428 Sync eng/common directory with azure-sdk-tools for PR 1136
  eng/common/scripts/Delete-RemoteBranches.ps1
Labels: Central-EngSys, EngSys

#427 Sync eng/common directory with azure-sdk-tools for PR 1135
  eng/common/TestResources/New-TestResources.ps1.md
  eng/common/TestResources/Remove-TestResources.ps1.md
  eng/common/scripts/Verify-Links.ps1
Labels: Central-EngSys, EngSys

#431 Sync eng/common directory with azure-sdk-tools for PR 1130
  eng/common/README.md
Labels: Central-EngSys, EngSys

#430 Sync eng/common directory with azure-sdk-tools for PR 1137
  eng/common/TestResources/AzurePowerShellV4/Utility.ps1
  eng/common/TestResources/Import-AzModules.ps1
  eng/common/TestResources/deploy-test-resources.yml
  eng/common/TestResources/remove-test-resources.yml
  eng/common/TestResources/setup-az-modules.yml
Labels: Central-EngSys, EngSys

#433 Sync eng/common directory with azure-sdk-tools for PR 1144
  eng/common/pipelines/templates/steps/install-pipeline-generation.yml
Labels: Central-EngSys, EngSys

#434 Add Check Enforcer timeout message.
  eng/CHECKENFORCER
Labels: Central-EngSys, EngSys

#436 Sync eng/common directory with azure-sdk-tools for PR 1146
  eng/common/TestResources/Remove-TestResources.ps1
Labels: Central-EngSys, EngSys

#437 Sync eng/common directory with azure-sdk-tools for PR 1148
  eng/common/README.md
Labels: Central-EngSys, EngSys

#440 Sync eng/common directory with azure-sdk-tools for PR 1158
  eng/common/pipelines/templates/steps/verify-path-length.yml
Labels: Central-EngSys, EngSys

#442 Sync eng/common directory with azure-sdk-tools for PR 1154
  eng/common/scripts/git-branch-push.ps1
  eng/common/scripts/modules/ChangeLog-Operations.psm1
Labels: Central-EngSys, EngSys
