Repository Azure/azure-sdk-for-android, pull requests merged in 2021-03, with the labels that each got.

#604 Add real time notification test app
  build.gradle
  samples/sample-chat-app/.gitignore
  samples/sample-chat-app/README.md
  samples/sample-chat-app/build.gradle
  samples/sample-chat-app/proguard-rules.pro
  samples/sample-chat-app/src/main/AndroidManifest.xml
  samples/sample-chat-app/src/main/java/com/azure/android/communication/chat/sampleapp/MainActivity.java
  samples/sample-chat-app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  samples/sample-chat-app/src/main/res/drawable/ic_launcher_background.xml
  samples/sample-chat-app/src/main/res/layout/activity_main.xml
  samples/sample-chat-app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  samples/sample-chat-app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  samples/sample-chat-app/src/main/res/mipmap-hdpi/ic_launcher.png
  samples/sample-chat-app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  samples/sample-chat-app/src/main/res/mipmap-mdpi/ic_launcher.png
  samples/sample-chat-app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  samples/sample-chat-app/src/main/res/mipmap-xhdpi/ic_launcher.png
  samples/sample-chat-app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  samples/sample-chat-app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  samples/sample-chat-app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  samples/sample-chat-app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  samples/sample-chat-app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  samples/sample-chat-app/src/main/res/values/colors.xml
  samples/sample-chat-app/src/main/res/values/strings.xml
  sdk/communication/azure-communication-chat/CHANGELOG.md
  sdk/communication/azure-communication-chat/build.gradle
  sdk/communication/azure-communication-common/CHANGELOG.md
  sdk/communication/azure-communication-common/build.gradle
  settings.gradle
Labels: Communication

#612 [Communication] - Token - Introduce CommunicationAccessToken
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/ChatParticipant.java
  sdk/communication/azure-communication-chat/swagger/swagger.json
  sdk/communication/azure-communication-common/CHANGELOG.md
  sdk/communication/azure-communication-common/build.gradle
  sdk/communication/azure-communication-common/src/main/java/com/azure/android/communication/common/AutoRefreshUserCredential.java
  sdk/communication/azure-communication-common/src/main/java/com/azure/android/communication/common/CommunicationAccessToken.java
  sdk/communication/azure-communication-common/src/main/java/com/azure/android/communication/common/CommunicationTokenCredential.java
  sdk/communication/azure-communication-common/src/main/java/com/azure/android/communication/common/CommunicationUserIdentifier.java
  sdk/communication/azure-communication-common/src/main/java/com/azure/android/communication/common/MicrosoftTeamsUserIdentifier.java
  sdk/communication/azure-communication-common/src/main/java/com/azure/android/communication/common/PhoneNumberIdentifier.java
  sdk/communication/azure-communication-common/src/main/java/com/azure/android/communication/common/StaticUserCredential.java
  sdk/communication/azure-communication-common/src/main/java/com/azure/android/communication/common/TokenParser.java
  sdk/communication/azure-communication-common/src/main/java/com/azure/android/communication/common/UnknownIdentifier.java
  sdk/communication/azure-communication-common/src/main/java/com/azure/android/communication/common/UserCredential.java
  sdk/communication/azure-communication-common/src/test/java/com/azure/android/communication/common/CommunicationTokenCredentialTest.java
Labels: Communication

#614 Sync eng/common directory with azure-sdk-tools for PR 1456
  eng/common/scripts/common.ps1
Labels: Central-EngSys, EngSys

#616 [Communication] - Identifier - Fixing up logic to match core
  sdk/communication/azure-communication-common/src/main/java/com/azure/android/communication/common/CommunicationUserIdentifier.java
  sdk/communication/azure-communication-common/src/main/java/com/azure/android/communication/common/MicrosoftTeamsUserIdentifier.java
  sdk/communication/azure-communication-common/src/main/java/com/azure/android/communication/common/PhoneNumberIdentifier.java
  sdk/communication/azure-communication-common/src/main/java/com/azure/android/communication/common/UnknownIdentifier.java
Labels: Communication

#621 Sync eng/common directory with azure-sdk-tools for PR 1459
  eng/common/scripts/SetTestPipelineVersion.ps1
Labels: Central-EngSys, EngSys

#623 Sync eng/common directory with azure-sdk-tools for PR 1467
  eng/common/scripts/SetTestPipelineVersion.ps1
Labels: Central-EngSys, EngSys

#622 Sync eng/common directory with azure-sdk-tools for PR 1465
  eng/common/pipelines/templates/steps/create-apireview.yml
Labels: Central-EngSys, EngSys

#615 Sync eng/common directory with azure-sdk-tools for PR 1448
  eng/common/scripts/Create-APIReview.ps1
Labels: Central-EngSys, EngSys

#624 Sync eng/common directory with azure-sdk-tools for PR 1461
  eng/common/scripts/job-matrix/job-matrix-functions.ps1
  eng/common/scripts/job-matrix/tests/job-matrix-functions.modification.tests.ps1
Labels: Central-EngSys, EngSys

#625 Sync eng/common directory with azure-sdk-tools for PR 1470
  eng/common/scripts/SetTestPipelineVersion.ps1
Labels: Central-EngSys, EngSys

#626 Sync eng/common directory with azure-sdk-tools for PR 1472
  eng/common/pipelines/templates/steps/set-test-pipeline-version.yml
Labels: Central-EngSys, EngSys

#630 [Communication]: Address Android API view comments
  sdk/communication/azure-communication-common/CHANGELOG.md
  sdk/communication/azure-communication-common/src/main/java/com/azure/android/communication/common/CommunicationAccessToken.java
  sdk/communication/azure-communication-common/src/main/java/com/azure/android/communication/common/CommunicationCloudEnvironment.java
  sdk/communication/azure-communication-common/src/main/java/com/azure/android/communication/common/CommunicationTokenCredential.java
  sdk/communication/azure-communication-common/src/main/java/com/azure/android/communication/common/CommunicationTokenRefreshOptions.java
  sdk/communication/azure-communication-common/src/main/java/com/azure/android/communication/common/CommunicationUserIdentifier.java
  sdk/communication/azure-communication-common/src/main/java/com/azure/android/communication/common/MicrosoftTeamsUserIdentifier.java
  sdk/communication/azure-communication-common/src/main/java/com/azure/android/communication/common/PhoneNumberIdentifier.java
  sdk/communication/azure-communication-common/src/main/java/com/azure/android/communication/common/UnknownIdentifier.java
Labels: Communication

#633 [Communication]: Update ChangeLog files for March Release
  sdk/communication/azure-communication-chat/CHANGELOG.md
  sdk/communication/azure-communication-common/CHANGELOG.md
Labels: Communication

#629 Sync eng/common directory with azure-sdk-tools for PR 1452
  eng/common/pipelines/templates/jobs/archetype-sdk-tests-generate.yml
  eng/common/pipelines/templates/steps/sparse-checkout.yml
  eng/common/scripts/job-matrix/samples/matrix-test.yml
Labels: Central-EngSys, EngSys

#634 Sync eng/common directory with azure-sdk-tools for PR 1475
  eng/common/pipelines/templates/steps/install-pipeline-generation.yml
Labels: Central-EngSys, EngSys

#637 Sync eng/common directory with azure-sdk-tools for PR 1479
  eng/common/scripts/ChangeLog-Operations.ps1
  eng/common/scripts/SemVer.ps1
Labels: Central-EngSys, EngSys

#652 Enable CI build for communication modules. Adding credential policy, tests and recordings for AsyncChatClient
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/ChatAsyncClient.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/ChatClientBuilder.java
  sdk/communication/azure-communication-chat/src/test/java/com/azure/android/communication/chat/ChatAsyncClientTest.java
  sdk/communication/azure-communication-chat/src/test/java/com/azure/android/communication/chat/ChatClientTestBase.java
  sdk/communication/azure-communication-chat/src/test/resources/session-records/ChatAsyncClientTest.canCreateNewThreadWithoutSettingRepeatabilityID[1].json
  sdk/communication/azure-communication-chat/src/test/resources/session-records/ChatAsyncClientTest.canCreateThreadWithResponse[1].json
  sdk/communication/azure-communication-chat/src/test/resources/session-records/ChatAsyncClientTest.canCreateThread[1].json
  sdk/communication/azure-communication-chat/src/test/resources/session-records/ChatAsyncClientTest.canDeleteChatThreadWithResponse[1].json
  sdk/communication/azure-communication-chat/src/test/resources/session-records/ChatAsyncClientTest.canDeleteChatThread[1].json
  sdk/communication/azure-communication-chat/src/test/resources/session-records/ChatAsyncClientTest.canGetChatThreadClient[1].json
  sdk/communication/azure-communication-chat/src/test/resources/session-records/ChatAsyncClientTest.canGetExistingChatThreadWithResponse[1].json
  sdk/communication/azure-communication-chat/src/test/resources/session-records/ChatAsyncClientTest.canGetExistingChatThread[1].json
  sdk/communication/azure-communication-chat/src/test/resources/session-records/ChatAsyncClientTest.canListChatThreadsWithMaxPage[1].json
  sdk/communication/azure-communication-chat/src/test/resources/session-records/ChatAsyncClientTest.canListChatThreads[1].json
  sdk/communication/azure-communication-chat/src/test/resources/session-records/ChatAsyncClientTest.canRepeatCreateThread[1].json
  sdk/communication/azure-communication-chat/src/test/resources/session-records/ChatAsyncClientTest.cannotCreateThreadWithNullOptions[1].json
  sdk/communication/azure-communication-chat/src/test/resources/session-records/ChatAsyncClientTest.cannotCreateThreadWithResponseWithNullOptions[1].json
  sdk/communication/azure-communication-chat/src/test/resources/session-records/ChatAsyncClientTest.cannotDeleteChatThreadWithNullId[1].json
  sdk/communication/azure-communication-chat/src/test/resources/session-records/ChatAsyncClientTest.cannotDeleteChatThreadWithResponseWithNullId[1].json
  sdk/communication/azure-communication-chat/src/test/resources/session-records/ChatAsyncClientTest.cannotGetChatThreadWithNullId[1].json
  sdk/communication/azure-communication-chat/src/test/resources/session-records/ChatAsyncClientTest.cannotGetChatThreadWithResponseWithNullId[1].json
  sdk/communication/azure-communication-chat/src/test/resources/session-records/ChatAsyncClientTest.getNotFoundOnNonExistingChatThreadWithResponse[1].json
  sdk/communication/azure-communication-chat/src/test/resources/session-records/ChatAsyncClientTest.getNotFoundOnNonExistingChatThread[1].json
  sdk/communication/ci.yml
Labels: Communication

#654 Sync eng/common directory with azure-sdk-tools for PR 1485
  eng/common/scripts/Collect-ChangeLogs.ps1
Labels: Central-EngSys, EngSys

#655 Adding JasonValue to type derived from ExpandableEnum, adding tests for async ChatThreadClient & Identifer-converter
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/ChatMessageType.java
  sdk/communication/azure-communication-chat/src/test/java/com/azure/android/communication/chat/ChatClientTestBase.java
  sdk/communication/azure-communication-chat/src/test/java/com/azure/android/communication/chat/ChatResponseMocker.java
  sdk/communication/azure-communication-chat/src/test/java/com/azure/android/communication/chat/ChatThreadAsyncClientTest.java
  sdk/communication/azure-communication-chat/src/test/java/com/azure/android/communication/chat/CommunicationIdentifierConverterTests.java
  sdk/communication/azure-communication-chat/src/test/resources/session-records/ChatThreadAsyncClientTest.canAddListAndRemoveMembersWithResponse[1].json
  sdk/communication/azure-communication-chat/src/test/resources/session-records/ChatThreadAsyncClientTest.canAddListAndRemoveMembers[1].json
  sdk/communication/azure-communication-chat/src/test/resources/session-records/ChatThreadAsyncClientTest.canAddSingleParticipantWithResponse[1].json
  sdk/communication/azure-communication-chat/src/test/resources/session-records/ChatThreadAsyncClientTest.canAddSingleParticipant[1].json
  sdk/communication/azure-communication-chat/src/test/resources/session-records/ChatThreadAsyncClientTest.canDeleteExistingMessageWithResponse[1].json
  sdk/communication/azure-communication-chat/src/test/resources/session-records/ChatThreadAsyncClientTest.canDeleteExistingMessage[1].json
  sdk/communication/azure-communication-chat/src/test/resources/session-records/ChatThreadAsyncClientTest.canListMessagesWithOptions[1].json
  sdk/communication/azure-communication-chat/src/test/resources/session-records/ChatThreadAsyncClientTest.canListMessages[1].json
  sdk/communication/azure-communication-chat/src/test/resources/session-records/ChatThreadAsyncClientTest.canListReadReceiptsWithOptions[1].json
  sdk/communication/azure-communication-chat/src/test/resources/session-records/ChatThreadAsyncClientTest.canListReadReceipts[1].json
  sdk/communication/azure-communication-chat/src/test/resources/session-records/ChatThreadAsyncClientTest.canSendReadReceiptWithResponse[1].json
  sdk/communication/azure-communication-chat/src/test/resources/session-records/ChatThreadAsyncClientTest.canSendReadReceipt[1].json
  sdk/communication/azure-communication-chat/src/test/resources/session-records/ChatThreadAsyncClientTest.canSendThenGetHtmlMessage[1].json
  sdk/communication/azure-communication-chat/src/test/resources/session-records/ChatThreadAsyncClientTest.canSendThenGetMessageWithResponse[1].json
  sdk/communication/azure-communication-chat/src/test/resources/session-records/ChatThreadAsyncClientTest.canSendThenGetMessage[1].json
  sdk/communication/azure-communication-chat/src/test/resources/session-records/ChatThreadAsyncClientTest.canSendTypingNotificationWithResponse[1].json
  sdk/communication/azure-communication-chat/src/test/resources/session-records/ChatThreadAsyncClientTest.canSendTypingNotification[1].json
  sdk/communication/azure-communication-chat/src/test/resources/session-records/ChatThreadAsyncClientTest.canUpdateExistingMessageWithResponse[1].json
  sdk/communication/azure-communication-chat/src/test/resources/session-records/ChatThreadAsyncClientTest.canUpdateExistingMessage[1].json
  sdk/communication/azure-communication-chat/src/test/resources/session-records/ChatThreadAsyncClientTest.canUpdateThreadWithResponse[1].json
  sdk/communication/azure-communication-chat/src/test/resources/session-records/ChatThreadAsyncClientTest.canUpdateThread[1].json
  sdk/communication/azure-communication-chat/src/test/resources/session-records/ChatThreadAsyncClientTest.cannotAddParticipantsWithNullOptions[1].json
  sdk/communication/azure-communication-chat/src/test/resources/session-records/ChatThreadAsyncClientTest.cannotAddParticipantsWithResponseWithNullOptions[1].json
  sdk/communication/azure-communication-chat/src/test/resources/session-records/ChatThreadAsyncClientTest.cannotDeleteMessageNullId[1].json
  sdk/communication/azure-communication-chat/src/test/resources/session-records/ChatThreadAsyncClientTest.cannotDeleteMessageWithRepsonseNullId[1].json
  sdk/communication/azure-communication-chat/src/test/resources/session-records/ChatThreadAsyncClientTest.cannotGetMessageNullId[1].json
  sdk/communication/azure-communication-chat/src/test/resources/session-records/ChatThreadAsyncClientTest.cannotGetMessageWithReponseNullId[1].json
  sdk/communication/azure-communication-chat/src/test/resources/session-records/ChatThreadAsyncClientTest.cannotRemoveParticipantWithNullUserWithResponse[1].json
  sdk/communication/azure-communication-chat/src/test/resources/session-records/ChatThreadAsyncClientTest.cannotRemoveParticipantWithNullUser[1].json
  sdk/communication/azure-communication-chat/src/test/resources/session-records/ChatThreadAsyncClientTest.cannotSendMessageWithNullOptions[1].json
  sdk/communication/azure-communication-chat/src/test/resources/session-records/ChatThreadAsyncClientTest.cannotSendMessageWithResponseWithNullOptions[1].json
  sdk/communication/azure-communication-chat/src/test/resources/session-records/ChatThreadAsyncClientTest.cannotSendReadReceiptWithNullMessageId[1].json
  sdk/communication/azure-communication-chat/src/test/resources/session-records/ChatThreadAsyncClientTest.cannotSendReadReceiptWithResponseWithNullMessageId[1].json
  sdk/communication/azure-communication-chat/src/test/resources/session-records/ChatThreadAsyncClientTest.cannotUpdateMessageNullId[1].json
  sdk/communication/azure-communication-chat/src/test/resources/session-records/ChatThreadAsyncClientTest.cannotUpdateMessageWithResponseNullId[1].json
  sdk/communication/azure-communication-chat/src/test/resources/session-records/ChatThreadAsyncClientTest.cannotUpdateThreadWithNullTopic[1].json
  sdk/communication/azure-communication-chat/src/test/resources/session-records/ChatThreadAsyncClientTest.cannotUpdateThreadWithResponseWithNullTopic[1].json
Labels: Communication

#656 Removing the temporary "handwritten" package given convenience-layer and tests are integrated
  build.gradle
  config/checkstyle/checkstyle-suppressions.xml
  eng/lint.xml
  sdk/communication/azure-communication-chat/build.gradle
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/handwritten/ChatAsyncClient.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/handwritten/ChatClient.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/handwritten/ChatClientBuilder.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/handwritten/ChatServiceVersion.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/handwritten/ChatThreadAsyncClient.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/handwritten/ChatThreadClient.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/handwritten/implementation/CommunicationBearerTokenCredential.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/handwritten/implementation/converters/AddChatParticipantsOptionsConverter.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/handwritten/implementation/converters/ChatMessageContentConverter.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/handwritten/implementation/converters/ChatMessageConverter.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/handwritten/implementation/converters/ChatMessageReadReceiptConverter.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/handwritten/implementation/converters/ChatParticipantConverter.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/handwritten/implementation/converters/ChatThreadConverter.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/handwritten/implementation/converters/CommunicationIdentifierConverter.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/handwritten/implementation/converters/CreateChatThreadOptionsConverter.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/handwritten/implementation/converters/CreateChatThreadResultConverter.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/handwritten/implementation/converters/SendChatMessageResultConverter.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/handwritten/models/AddChatParticipantsOptions.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/handwritten/models/ChatMessage.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/handwritten/models/ChatMessageReadReceipt.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/handwritten/models/ChatParticipant.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/handwritten/models/ChatThread.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/handwritten/models/CreateChatThreadOptions.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/handwritten/models/CreateChatThreadResult.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/handwritten/models/ListParticipantsOptions.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/handwritten/models/ListReadReceiptOptions.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/handwritten/models/package-info.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/handwritten/package-info.java
  sdk/communication/azure-communication-chat/src/test/java/com/azure/android/communication/chat/handwritten/ChatAsyncClientTest.java
  sdk/communication/azure-communication-chat/src/test/java/com/azure/android/communication/chat/handwritten/ChatClientTest.java
  sdk/communication/azure-communication-chat/src/test/java/com/azure/android/communication/chat/handwritten/ChatClientTestBase.java
  sdk/communication/azure-communication-chat/src/test/java/com/azure/android/communication/chat/handwritten/ChatResponseMocker.java
  sdk/communication/azure-communication-chat/src/test/java/com/azure/android/communication/chat/handwritten/ChatThreadAsyncClientTest.java
  sdk/communication/azure-communication-chat/src/test/java/com/azure/android/communication/chat/handwritten/ChatThreadClientTest.java
  sdk/communication/azure-communication-chat/src/test/java/com/azure/android/communication/chat/handwritten/CommunicationIdentifierConverterTests.java
  sdk/communication/azure-communication-chat/src/test/java/com/azure/android/communication/chat/handwritten/CommunicationLoggerPolicy.java
  sdk/communication/azure-communication-chat/src/test/java/com/azure/android/communication/chat/handwritten/implementation/ChatOptionsProvider.java
Labels: Communication

#636 Sync eng/common directory with azure-sdk-tools for PR 1458
  eng/common/pipelines/templates/steps/set-default-branch.yml
  eng/common/pipelines/templates/steps/verify-links.yml
  eng/common/scripts/Verify-Links.ps1
Labels: Central-EngSys, EngSys

#658 Sync eng/common directory with azure-sdk-tools for PR 1490
  eng/common/pipelines/templates/steps/publish-artifact.yml
Labels: Central-EngSys, EngSys

#610 Sync eng/common directory with azure-sdk-tools for PR 1418
  eng/common/scripts/Package-Properties.ps1
  eng/common/scripts/Prepare-Release.ps1
  eng/common/scripts/Update-ChangeLog.ps1
Labels: Central-EngSys, EngSys

#661 azure-communiication-chat: returning Page from simple paged methods
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/ChatAsyncClient.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/ChatClient.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/ChatThreadAsyncClient.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/ChatThreadClient.java
Labels: Communication

#663 Sync eng/common directory with azure-sdk-tools for PR 1496
  eng/common/scripts/Package-Properties.ps1
Labels: Central-EngSys, EngSys

#664 Sync eng/common directory with azure-sdk-tools for PR 1463
  eng/common/pipelines/templates/jobs/archetype-sdk-tests-generate.yml
  eng/common/scripts/job-matrix/Create-JobMatrix.ps1
  eng/common/scripts/job-matrix/README.md
  eng/common/scripts/job-matrix/job-matrix-functions.ps1
  eng/common/scripts/job-matrix/samples/matrix-test.yml
  eng/common/scripts/job-matrix/samples/matrix.json
  eng/common/scripts/job-matrix/tests/job-matrix-functions.modification.tests.ps1
  eng/common/scripts/job-matrix/tests/job-matrix-functions.tests.ps1
  eng/common/scripts/job-matrix/tests/test-import-matrix.json
Labels: Central-EngSys, EngSys

#670 Sync eng/common directory with azure-sdk-tools for PR 1498
  eng/common/scripts/job-matrix/job-matrix-functions.ps1
  eng/common/scripts/job-matrix/tests/job-matrix-functions.modification.tests.ps1
  eng/common/scripts/job-matrix/tests/job-matrix-functions.tests.ps1
Labels: Central-EngSys, EngSys

#673 Sync eng/common directory with azure-sdk-tools for PR 1489
  eng/common/pipelines/templates/steps/create-pull-request.yml
  eng/common/scripts/Submit-PullRequest.ps1
Labels: Central-EngSys, EngSys

#676 Updated azure-core versions in Gradle files, README and CHANGELOG in preparation for the 1.0.0-beta.4 release.
  sdk/core/azure-core-credential/CHANGELOG.md
  sdk/core/azure-core-credential/README.md
  sdk/core/azure-core-credential/build.gradle
  sdk/core/azure-core-http-httpurlconnection/CHANGELOG.md
  sdk/core/azure-core-http-httpurlconnection/README.md
  sdk/core/azure-core-http-httpurlconnection/build.gradle
  sdk/core/azure-core-http-okhttp/CHANGELOG.md
  sdk/core/azure-core-http-okhttp/README.md
  sdk/core/azure-core-http-okhttp/build.gradle
  sdk/core/azure-core-http/CHANGELOG.md
  sdk/core/azure-core-http/README.md
  sdk/core/azure-core-http/build.gradle
  sdk/core/azure-core-jackson/CHANGELOG.md
  sdk/core/azure-core-jackson/README.md
  sdk/core/azure-core-jackson/build.gradle
  sdk/core/azure-core-logging/CHANGELOG.md
  sdk/core/azure-core-logging/README.md
  sdk/core/azure-core-logging/build.gradle
  sdk/core/azure-core-rest/CHANGELOG.md
  sdk/core/azure-core-rest/README.md
  sdk/core/azure-core-rest/build.gradle
  sdk/core/azure-core-test/CHANGELOG.md
  sdk/core/azure-core-test/README.md
  sdk/core/azure-core-test/build.gradle
  sdk/core/azure-core/CHANGELOG.md
  sdk/core/azure-core/README.md
  sdk/core/azure-core/build.gradle
Labels: Azure.Core

#677 Add azure-core-http to ci.yml
  sdk/core/ci.yml
Labels: Azure.Core

#675 Regenerate from Java swagger and Readme.md with expected manual changes
  config/checkstyle/checkstyle-suppressions.xml
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/ChatThreadAsyncClient.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/implementation/AzureCommunicationChatServiceImpl.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/implementation/AzureCommunicationChatServiceImplBuilder.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/implementation/ChatImpl.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/implementation/ChatThreadImpl.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/implementation/converters/AddChatParticipantsResultConverter.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/implementation/converters/ChatErrorConverter.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/implementation/converters/CreateChatThreadResultConverter.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/implementation/converters/SendChatMessageResultConverter.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/implementation/models/AddChatParticipantsResult.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/implementation/models/ChatMessage.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/implementation/models/ChatMessageContent.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/implementation/models/ChatMessageReadReceipt.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/implementation/models/ChatParticipant.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/implementation/models/ChatThreadProperties.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/implementation/models/ChatThreadsItemCollection.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/implementation/models/CommunicationError.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/implementation/models/CommunicationErrorResponse.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/implementation/models/CommunicationErrorResponseException.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/implementation/models/CreateChatThreadErrors.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/implementation/models/CreateChatThreadOptions.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/implementation/models/CreateChatThreadResult.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/implementation/models/IndividualStatusResponse.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/implementation/models/MultiStatusResponse.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/AddChatParticipantsErrors.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/AddChatParticipantsResult.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/ChatError.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/ChatMessageType.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/ChatThreadItem.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/CommunicationErrorResponseException.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/CreateChatThreadResult.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/Error.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/SendChatMessageResult.java
  sdk/communication/azure-communication-chat/src/test/java/com/azure/android/communication/chat/ChatThreadAsyncClientTest.java
  sdk/communication/azure-communication-chat/src/test/java/com/azure/android/communication/chat/implementation/ChatAsyncImplClientTest.java
  sdk/communication/azure-communication-chat/swagger/README.md
  sdk/communication/azure-communication-chat/swagger/swagger.json
Labels: Communication

#678 Sync eng/common directory with azure-sdk-tools for PR 1502
  eng/common/scripts/ChangeLog-Operations.ps1
Labels: Central-EngSys, EngSys

#684 Sync eng/common directory with azure-sdk-tools for PR 1476
  eng/common/scripts/Helpers/DevOps-WorkItem-Helpers.ps1
  eng/common/scripts/Package-Properties.ps1
  eng/common/scripts/Prepare-Release.ps1
  eng/common/scripts/Update-DevOps-Release-WorkItem.ps1
Labels: Central-EngSys, EngSys

#685 azure-communication-common: Using CompletableFuture as return type for UserToken::getToken().
  sdk/communication/azure-communication-common/build.gradle
  sdk/communication/azure-communication-common/src/main/java/com/azure/android/communication/common/AutoRefreshUserCredential.java
  sdk/communication/azure-communication-common/src/main/java/com/azure/android/communication/common/StaticUserCredential.java
  sdk/communication/azure-communication-common/src/main/java/com/azure/android/communication/common/UserCredential.java
Labels: Communication

#686 Sync eng/common directory with azure-sdk-tools for PR 1514
  eng/common/scripts/job-matrix/job-matrix-functions.ps1
  eng/common/scripts/job-matrix/tests/job-matrix-functions.modification.tests.ps1
  eng/common/scripts/job-matrix/tests/job-matrix-functions.tests.ps1
Labels: Central-EngSys, EngSys

#696 Updated Azure Core version in CHANGELOGs and build.gradle files
  sdk/core/azure-core-credential/CHANGELOG.md
  sdk/core/azure-core-credential/build.gradle
  sdk/core/azure-core-http-httpurlconnection/CHANGELOG.md
  sdk/core/azure-core-http-httpurlconnection/build.gradle
  sdk/core/azure-core-http-okhttp/CHANGELOG.md
  sdk/core/azure-core-http-okhttp/build.gradle
  sdk/core/azure-core-http/CHANGELOG.md
  sdk/core/azure-core-http/build.gradle
  sdk/core/azure-core-jackson/CHANGELOG.md
  sdk/core/azure-core-jackson/build.gradle
  sdk/core/azure-core-logging/CHANGELOG.md
  sdk/core/azure-core-logging/build.gradle
  sdk/core/azure-core-rest/CHANGELOG.md
  sdk/core/azure-core-rest/build.gradle
  sdk/core/azure-core-test/CHANGELOG.md
  sdk/core/azure-core-test/build.gradle
  sdk/core/azure-core/CHANGELOG.md
  sdk/core/azure-core/build.gradle
Labels: Azure.Core

#691 Updating azure-communication-common module to be in sync with beta.7 (released from master) and additional improvements
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/ChatClientBuilder.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/implementation/converters/CommunicationIdentifierConverter.java
  sdk/communication/azure-communication-common/CHANGELOG.md
  sdk/communication/azure-communication-common/README.md
  sdk/communication/azure-communication-common/build.gradle
  sdk/communication/azure-communication-common/src/main/java/com/azure/android/communication/common/AutoRefreshUserCredential.java
  sdk/communication/azure-communication-common/src/main/java/com/azure/android/communication/common/CommunicationAccessToken.java
  sdk/communication/azure-communication-common/src/main/java/com/azure/android/communication/common/CommunicationCloudEnvironment.java
  sdk/communication/azure-communication-common/src/main/java/com/azure/android/communication/common/CommunicationCloudEnvironmentModel.java
  sdk/communication/azure-communication-common/src/main/java/com/azure/android/communication/common/CommunicationIdentifierModel.java
  sdk/communication/azure-communication-common/src/main/java/com/azure/android/communication/common/CommunicationIdentifierSerializer.java
  sdk/communication/azure-communication-common/src/main/java/com/azure/android/communication/common/CommunicationTokenCredential.java
  sdk/communication/azure-communication-common/src/main/java/com/azure/android/communication/common/CommunicationTokenRefreshOptions.java
  sdk/communication/azure-communication-common/src/main/java/com/azure/android/communication/common/CommunicationUserIdentifier.java
  sdk/communication/azure-communication-common/src/main/java/com/azure/android/communication/common/CommunicationUserIdentifierModel.java
  sdk/communication/azure-communication-common/src/main/java/com/azure/android/communication/common/MicrosoftTeamsUserIdentifier.java
  sdk/communication/azure-communication-common/src/main/java/com/azure/android/communication/common/MicrosoftTeamsUserIdentifierModel.java
  sdk/communication/azure-communication-common/src/main/java/com/azure/android/communication/common/PhoneNumberIdentifier.java
  sdk/communication/azure-communication-common/src/main/java/com/azure/android/communication/common/PhoneNumberIdentifierModel.java
  sdk/communication/azure-communication-common/src/main/java/com/azure/android/communication/common/StaticUserCredential.java
  sdk/communication/azure-communication-common/src/main/java/com/azure/android/communication/common/TokenParser.java
  sdk/communication/azure-communication-common/src/main/java/com/azure/android/communication/common/UnknownIdentifier.java
  sdk/communication/azure-communication-common/src/main/java/com/azure/android/communication/common/UserCredential.java
  sdk/communication/azure-communication-common/src/test/java/com/azure/android/communication/common/CommunicationIdentifierSerializerTests.java
  sdk/communication/azure-communication-common/src/test/java/com/azure/android/communication/common/CommunicationIdentifierTests.java
  sdk/communication/azure-communication-common/src/test/java/com/azure/android/communication/common/CommunicationTokenCredentialTest.java
  sdk/communication/azure-communication-common/src/test/java/com/azure/android/communication/common/IdentifierDeserializationExceptionTests.java
  sdk/communication/azure-communication-common/src/test/java/com/azure/android/communication/common/IdentifierSerialzationExceptionTests.java
  sdk/communication/azure-communication-common/src/test/java/com/azure/android/communication/common/JwtTokenMocker.java
  sdk/communication/azure-communication-common/src/test/java/com/azure/android/communication/common/TeamsUserIdentifierSerializationTests.java
  sdk/communication/azure-communication-common/src/test/java/com/azure/android/communication/common/TokenParserTests.java
Labels: Communication

#697 Removed unused properties files from Core and Communication libraries.
  samples/sample-chat-app/build.gradle
  sdk/communication/azure-communication-chat/src/main/resources/azure-communication-chat.properties
  sdk/core/azure-core-credential/src/main/resources/azure-core.properties
  sdk/core/azure-core-http/src/main/resources/azure-core.properties
  sdk/core/azure-core-jackson/src/main/resources/azure-core.properties
  sdk/core/azure-core-logging/src/main/resources/azure-core.properties
  sdk/core/azure-core-rest/src/main/resources/azure-core.properties
  sdk/core/azure-core/src/main/resources/azure-core.properties
Labels: Azure.Core, Communication

#680 Add trouter convenience layer to SDK
  build.gradle
  eng/code-quality-reports/src/main/java/com/azure/tools/checkstyle/checks/ExternalDependencyExposedCheck.java
  sdk/communication/azure-communication-chat/build.gradle
  sdk/communication/azure-communication-chat/env-prod.properties
  sdk/communication/azure-communication-chat/env-test.properties
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/ChatAsyncClient.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/ChatClient.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/ChatClientBuilder.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/signaling/CommunicationListener.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/signaling/CommunicationSignalingClient.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/signaling/ConnectionState.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/signaling/RealTimeNotificationCallback.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/signaling/SignalingClient.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/signaling/TrouterUtils.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/signaling/package-info.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/signaling/properties/ChatEventId.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/signaling/properties/package-info.java
Labels: Communication

#699 Updated ACS dependencies, versions and CHANGELOGs.
  build.gradle
  eng/code-quality-reports/gradle/wrapper/gradle-wrapper.properties
  gradle/wrapper/gradle-wrapper.properties
  sdk/communication/azure-communication-chat/CHANGELOG.md
  sdk/communication/azure-communication-chat/README.md
  sdk/communication/azure-communication-chat/build.gradle
  sdk/communication/azure-communication-chat/pom.xml
  sdk/communication/azure-communication-common/CHANGELOG.md
  sdk/communication/azure-communication-common/README.md
  sdk/communication/azure-communication-common/build.gradle
Labels: Communication

#700 Sync eng/common directory with azure-sdk-tools for PR 1517
  eng/common/scripts/Update-ChangeLog.ps1
Labels: Central-EngSys, EngSys

#701 Sync eng/common directory with azure-sdk-tools for PR 1478
  eng/common/pipelines/templates/steps/create-pull-request.yml
  eng/common/scripts/Invoke-GitHubAPI.ps1
  eng/common/scripts/Submit-PullRequest.ps1
Labels: Central-EngSys, EngSys

#682 Sync eng/common directory with azure-sdk-tools for PR 1508
  eng/common/pipelines/templates/steps/create-apireview.yml
  eng/common/scripts/Create-APIReview.ps1
Labels: Central-EngSys, EngSys

#702 Sync eng/common directory with azure-sdk-tools for PR 1493
  eng/common/pipelines/templates/steps/publish-blobs.yml
  eng/common/scripts/check-spelling-in-changed-files.ps1
  eng/common/scripts/copy-docs-to-blobstorage.ps1
Labels: Central-EngSys, EngSys

#705 Updated Azure Core versions to `1.0.0-beta.5` in preparation for release. Updated CHANGELOGs and READMEs.
  sdk/communication/azure-communication-chat/CHANGELOG.md
  sdk/core/azure-core-credential/CHANGELOG.md
  sdk/core/azure-core-credential/README.md
  sdk/core/azure-core-http-httpurlconnection/CHANGELOG.md
  sdk/core/azure-core-http-httpurlconnection/README.md
  sdk/core/azure-core-http-okhttp/CHANGELOG.md
  sdk/core/azure-core-http-okhttp/README.md
  sdk/core/azure-core-http/CHANGELOG.md
  sdk/core/azure-core-http/README.md
  sdk/core/azure-core-jackson/CHANGELOG.md
  sdk/core/azure-core-jackson/README.md
  sdk/core/azure-core-logging/CHANGELOG.md
  sdk/core/azure-core-logging/README.md
  sdk/core/azure-core-rest/CHANGELOG.md
  sdk/core/azure-core-rest/README.md
  sdk/core/azure-core-test/CHANGELOG.md
  sdk/core/azure-core-test/README.md
  sdk/core/azure-core/CHANGELOG.md
  sdk/core/azure-core/README.md
Labels: Azure.Core, Communication

#704 Sync eng/common directory with azure-sdk-tools for PR 1521
  eng/common/scripts/job-matrix/README.md
  eng/common/scripts/job-matrix/job-matrix-functions.ps1
  eng/common/scripts/job-matrix/tests/job-matrix-functions.modification.tests.ps1
Labels: Central-EngSys, EngSys

#706 Update trouter schema, use trouter from maven central
  build.gradle
  samples/sample-chat-app/build.gradle
  samples/sample-chat-app/src/main/java/com/azure/android/communication/chat/sampleapp/MainActivity.java
  sdk/communication/azure-communication-chat/build.gradle
  sdk/communication/azure-communication-chat/env-prod.properties
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/signaling/CommunicationListener.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/signaling/RealTimeNotificationCallback.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/signaling/TrouterUtils.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/signaling/chatevents/BaseEvent.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/signaling/chatevents/ChatMessageDeletedEvent.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/signaling/chatevents/ChatMessageEditedEvent.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/signaling/chatevents/ChatMessageReceivedEvent.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/signaling/chatevents/ChatThreadCreatedEvent.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/signaling/chatevents/ChatThreadDeletedEvent.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/signaling/chatevents/ChatThreadEvent.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/signaling/chatevents/ChatThreadPropertiesUpdatedEvent.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/signaling/chatevents/ChatUserEvent.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/signaling/chatevents/ParticipantsAddedEvent.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/signaling/chatevents/ParticipantsRemovedEvent.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/signaling/chatevents/ReadReceiptReceivedEvent.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/signaling/chatevents/TypingIndicatorReceivedEvent.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/signaling/chatevents/package-info.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/signaling/properties/ChatParticipant.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/signaling/properties/ChatThreadProperties.java
Labels: Communication

#707 Improve build.gradle readability and Update Azure Core versions after 1.0.0-beta.5 release.
  build.gradle
  eng/code-quality-reports/build.gradle
  samples/sample-chat-app/build.gradle
  sdk/communication/azure-communication-chat/build.gradle
  sdk/communication/azure-communication-common/build.gradle
  sdk/core/azure-core-credential/CHANGELOG.md
  sdk/core/azure-core-credential/build.gradle
  sdk/core/azure-core-http-httpurlconnection/CHANGELOG.md
  sdk/core/azure-core-http-httpurlconnection/build.gradle
  sdk/core/azure-core-http-okhttp/CHANGELOG.md
  sdk/core/azure-core-http-okhttp/build.gradle
  sdk/core/azure-core-http/CHANGELOG.md
  sdk/core/azure-core-http/build.gradle
  sdk/core/azure-core-jackson/CHANGELOG.md
  sdk/core/azure-core-jackson/build.gradle
  sdk/core/azure-core-logging/CHANGELOG.md
  sdk/core/azure-core-logging/build.gradle
  sdk/core/azure-core-rest/CHANGELOG.md
  sdk/core/azure-core-rest/build.gradle
  sdk/core/azure-core-test/CHANGELOG.md
  sdk/core/azure-core-test/build.gradle
  sdk/core/azure-core/CHANGELOG.md
  sdk/core/azure-core/build.gradle
Labels: Azure.Core, Communication

#703 Sync eng/common directory with azure-sdk-tools for PR 1477
  eng/common/pipelines/templates/steps/create-pull-request.yml
  eng/common/pipelines/templates/steps/docs-metadata-release.yml
  eng/common/pipelines/templates/steps/git-push-changes.yml
  eng/common/pipelines/templates/steps/set-default-branch.yml
  eng/common/scripts/git-branch-push.ps1
Labels: Central-EngSys, EngSys

#708 fix signaling recipient format, shared history time, and communicationIdentifier
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/signaling/TrouterUtils.java
Labels: Communication

#709 Sync eng/common directory with azure-sdk-tools for PR 1527
  eng/common/pipelines/templates/jobs/archetype-sdk-tests-generate.yml
Labels: Central-EngSys, EngSys

#710 [Communication]: Bump up version number in build.gradle and changelog for chat and common
  sdk/communication/azure-communication-chat/CHANGELOG.md
  sdk/communication/azure-communication-chat/README.md
  sdk/communication/azure-communication-chat/build.gradle
  sdk/communication/azure-communication-common/CHANGELOG.md
  sdk/communication/azure-communication-common/README.md
  sdk/communication/azure-communication-common/build.gradle
Labels: Communication

#711 Update naming, add unit test for identifier parsing
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/signaling/TrouterUtils.java
  sdk/communication/azure-communication-chat/src/test/java/com/azure/android/communication/chat/signaling/TrouterUtilsTest.java
Labels: Communication
