Repository Azure/azure-sdk-for-android, pull requests merged in 2021-05, with the labels that each got.

#762 Sync eng/common directory with azure-sdk-tools for PR 1579
  eng/common/pipelines/templates/steps/daily-dev-build-variable.yml
Labels: Central-EngSys, EngSys

#765 Sync eng/common directory with azure-sdk-tools for PR 1524
  eng/common/scripts/ChangeLog-Operations.ps1
Labels: Central-EngSys, EngSys

#767 Sync eng/common directory with azure-sdk-tools for PR 1596
  eng/common/pipelines/templates/steps/daily-dev-build-variable.yml
Labels: Central-EngSys, EngSys

#766 Extend Check Enforcer timeout
  eng/CHECKENFORCER
Labels: Central-EngSys, EngSys

#769 Sync eng/common directory with azure-sdk-tools for PR 1597
  eng/common/scripts/Prepare-Release.ps1
  eng/common/scripts/Update-DevOps-Release-WorkItem.ps1
Labels: Central-EngSys, EngSys

#771 Sync eng/common directory with azure-sdk-tools for PR 1594
  eng/common/pipelines/templates/steps/create-pull-request.yml
  eng/common/pipelines/templates/steps/sparse-checkout.yml
Labels: Central-EngSys, EngSys

#772 Sync eng/common directory with azure-sdk-tools for PR 1598
  eng/common/pipelines/templates/jobs/archetype-sdk-tests-generate.yml
Labels: Central-EngSys, EngSys

#727 refactor signaling package
  samples/sample-chat-app/build.gradle
  samples/sample-chat-app/src/main/java/com/azure/android/communication/chat/sampleapp/MainActivity.java
  sdk/communication/azure-communication-chat/CHANGELOG.md
  sdk/communication/azure-communication-chat/README.md
  sdk/communication/azure-communication-chat/env-prod.properties
  sdk/communication/azure-communication-chat/env-test.properties
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/ChatAsyncClient.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/ChatClient.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/ChatClientBuilder.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/ChatThreadClientBuilder.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/implementation/signaling/CommunicationListener.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/implementation/signaling/CommunicationSignalingClient.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/implementation/signaling/ConnectionState.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/implementation/signaling/EventAccessorHelper.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/implementation/signaling/SignalingClient.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/implementation/signaling/TrouterUtils.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/implementation/signaling/package-info.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/BaseEvent.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/ChatEventType.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/ChatMessageDeletedEvent.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/ChatMessageEditedEvent.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/ChatMessageReceivedEvent.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/ChatThreadCreatedEvent.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/ChatThreadDeletedEvent.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/ChatThreadEvent.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/ChatThreadPropertiesUpdatedEvent.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/ChatUserEvent.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/ParticipantsAddedEvent.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/ParticipantsRemovedEvent.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/ReadReceiptReceivedEvent.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/RealTimeNotificationCallback.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/TypingIndicatorReceivedEvent.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/signaling/TrouterUtils.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/signaling/chatevents/BaseEvent.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/signaling/chatevents/ChatMessageDeletedEvent.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/signaling/chatevents/ChatMessageEditedEvent.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/signaling/chatevents/ChatMessageReceivedEvent.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/signaling/chatevents/ChatThreadCreatedEvent.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/signaling/chatevents/ChatThreadDeletedEvent.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/signaling/chatevents/ChatThreadPropertiesUpdatedEvent.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/signaling/chatevents/ChatUserEvent.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/signaling/chatevents/ParticipantsAddedEvent.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/signaling/chatevents/ParticipantsRemovedEvent.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/signaling/chatevents/ReadReceiptReceivedEvent.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/signaling/chatevents/TypingIndicatorReceivedEvent.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/signaling/chatevents/package-info.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/signaling/package-info.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/signaling/properties/ChatEventId.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/signaling/properties/ChatParticipant.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/signaling/properties/ChatThreadProperties.java
  sdk/communication/azure-communication-chat/src/samples/java/com/azure/android/communication/chat/ReadmeSamples.java
  sdk/communication/azure-communication-chat/src/test/java/com/azure/android/communication/chat/implementation/signaling/TrouterUtilsTest.java
Labels: Communication

#774 Sync eng/common directory with azure-sdk-tools for PR 1585
  eng/common/pipelines/templates/steps/docs-metadata-release.yml
  eng/common/pipelines/templates/steps/sparse-checkout.yml
Labels: Central-EngSys, EngSys

#778 Sync eng/common directory with azure-sdk-tools for PR 1615
  eng/common/pipelines/templates/jobs/docindex.yml
Labels: Central-EngSys, EngSys

#777 Added the ServiceVersion interface to Azure Core.
  sdk/core/azure-core/src/main/java/com/azure/android/core/util/ServiceVersion.java
Labels: Azure.Core

#781 Sync eng/common directory with azure-sdk-tools for PR 1627
  eng/common/pipelines/templates/steps/sparse-checkout.yml
Labels: Central-EngSys, EngSys

#782 Sync eng/common directory with azure-sdk-tools for PR 1629
  eng/common/scripts/ChangeLog-Operations.ps1
Labels: Central-EngSys, EngSys

#784 Sync eng/common directory with azure-sdk-tools for PR 1635
  eng/common/scripts/Update-DocsMsPackages.ps1
  eng/common/scripts/common.ps1
Labels: Central-EngSys, EngSys

#779 Adding support for async stream, pagination types and updating Chat list* APIs to use it.
  eng/code-quality-reports/src/main/java/com/azure/tools/checkstyle/checks/ServiceClientCheck.java
  samples/sample-chat-app/src/main/java/com/azure/android/communication/chat/sampleapp/MainActivity.java
  sdk/communication/azure-communication-chat/CHANGELOG.md
  sdk/communication/azure-communication-chat/README.md
  sdk/communication/azure-communication-chat/build.gradle
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/ChatAsyncClient.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/ChatClient.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/ChatThreadAsyncClient.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/ChatThreadClient.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/implementation/CFBackedPageAsyncStream.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/implementation/ChatImpl.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/implementation/ChatThreadImpl.java
  sdk/communication/azure-communication-chat/src/samples/java/com/azure/android/communication/chat/ReadmeSamples.java
  sdk/communication/azure-communication-chat/src/test/java/com/azure/android/communication/chat/ChatAsyncClientTest.java
  sdk/communication/azure-communication-chat/src/test/java/com/azure/android/communication/chat/ChatClientTestBase.java
  sdk/communication/azure-communication-chat/src/test/java/com/azure/android/communication/chat/ChatThreadAsyncClientTest.java
  sdk/communication/azure-communication-chat/src/test/java/com/azure/android/communication/chat/implementation/ChatAsyncImplClientTest.java
  sdk/communication/azure-communication-chat/src/test/resources/session-records/ChatThreadAsyncClientTest.canAddListAndRemoveParticipantsWithResponse[1].json
  sdk/communication/azure-communication-chat/src/test/resources/session-records/ChatThreadAsyncClientTest.canAddListAndRemoveParticipants[1].json
  sdk/communication/azure-communication-common/build.gradle
  sdk/core/azure-core-rest/build.gradle
  sdk/core/azure-core-rest/src/main/java/com/azure/android/core/rest/HttpResponseMapper.java
  sdk/core/azure-core-rest/src/main/java/com/azure/android/core/rest/Page.java
  sdk/core/azure-core-rest/src/main/java/com/azure/android/core/rest/annotation/ReturnValueWireType.java
  sdk/core/azure-core-rest/src/main/java/com/azure/android/core/rest/implementation/ItemPage.java
  sdk/core/azure-core-rest/src/main/java/com/azure/android/core/rest/util/paging/PagedAsyncStream.java
  sdk/core/azure-core-rest/src/main/java/com/azure/android/core/rest/util/paging/PagedIterable.java
  sdk/core/azure-core-rest/src/main/java/com/azure/android/core/rest/util/paging/PagedResponse.java
  sdk/core/azure-core-rest/src/main/java/com/azure/android/core/rest/util/paging/PagedResponseBase.java
  sdk/core/azure-core-rest/src/main/java/com/azure/android/core/rest/util/paging/package-info.java
  sdk/core/azure-core-rest/src/test/java/com/azure/android/core/rest/HttpResponseMapperTests.java
  sdk/core/azure-core-rest/src/test/java/com/azure/android/core/rest/util/paging/CFBackedPageAsyncStream.java
  sdk/core/azure-core-rest/src/test/java/com/azure/android/core/rest/util/paging/CFStringPageRetriever.java
  sdk/core/azure-core-rest/src/test/java/com/azure/android/core/rest/util/paging/PagedAsyncStreamTests.java
  sdk/core/azure-core-rest/src/test/java/com/azure/android/core/rest/util/paging/PagedIterableTests.java
  sdk/core/azure-core-rest/src/test/java/com/azure/android/core/rest/util/paging/StringPageRetriever.java
  sdk/core/azure-core/src/main/java/com/azure/android/core/util/AsyncStream.java
  sdk/core/azure-core/src/main/java/com/azure/android/core/util/AsyncStreamHandler.java
  sdk/core/azure-core/src/main/java/com/azure/android/core/util/BiConsumer.java
  sdk/core/azure-core/src/main/java/com/azure/android/core/util/Function.java
  sdk/core/azure-core/src/main/java/com/azure/android/core/util/Predicate.java
  sdk/core/azure-core/src/main/java/com/azure/android/core/util/paging/Page.java
  sdk/core/azure-core/src/main/java/com/azure/android/core/util/paging/PagedAsyncStreamCore.java
Labels: Azure.Core, Communication

#785 Sync eng/common directory with azure-sdk-tools for PR 1606
  eng/common/TestResources/AzurePowerShellV4/Utility.ps1
  eng/common/TestResources/Import-AzModules.ps1
  eng/common/TestResources/deploy-test-resources.yml
  eng/common/TestResources/remove-test-resources.yml
  eng/common/TestResources/setup-environments.yml
  eng/common/pipelines/templates/steps/cache-ps-modules.yml
  eng/common/scripts/Helpers/PSModule-Helpers.ps1
  eng/common/scripts/Import-AzModules.ps1
Labels: Central-EngSys, EngSys

#786 Update Android Chat SDK APIs to follow JAVA
  samples/sample-chat-app/src/main/java/com/azure/android/communication/chat/sampleapp/MainActivity.java
  sdk/communication/azure-communication-chat/CHANGELOG.md
  sdk/communication/azure-communication-chat/README.md
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/ChatThreadAsyncClient.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/ChatThreadClient.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/implementation/converters/AddChatParticipantsOptionsConverter.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/AddChatParticipantsOptions.java
  sdk/communication/azure-communication-chat/src/samples/java/com/azure/android/communication/chat/ReadmeSamples.java
  sdk/communication/azure-communication-chat/src/test/java/com/azure/android/communication/chat/ChatClientTestBase.java
  sdk/communication/azure-communication-chat/src/test/java/com/azure/android/communication/chat/ChatThreadAsyncClientTest.java
Labels: Communication

#768 [Communication]: Update Chat Swagger ReadMe.md to use latest autorest release
  sdk/communication/azure-communication-chat/swagger/README.md
Labels: Communication

#780 Introduced `ChatServiceVersion` and added APIs to use it in client builders.
  sdk/communication/azure-communication-chat/CHANGELOG.md
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/ChatClientBuilder.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/ChatServiceVersion.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/ChatThreadClientBuilder.java
Labels: Communication
