Repository Azure/azure-sdk-for-android, pull requests merged in 2021-11, with the labels that each got.

#917 Sync eng/common directory with azure-sdk-tools for PR 2177
  eng/common/scripts/Invoke-GitHubAPI.ps1
Labels: EngSys, Central-EngSys

#918 Sync eng/common directory with azure-sdk-tools for PR 2203
  eng/common/pipelines/templates/steps/sparse-checkout.yml
Labels: EngSys, Central-EngSys

#919 Sync eng/common directory with azure-sdk-tools for PR 2179
  eng/common/pipelines/templates/steps/docker-pull-image.yml
  eng/common/scripts/Update-DocsMsPackages.ps1
Labels: EngSys, Central-EngSys

#920 Sync eng/common directory with azure-sdk-tools for PR 2053
  eng/common/TestResources/New-TestResources.ps1
Labels: EngSys, Central-EngSys

#921 Sync eng/common directory with azure-sdk-tools for PR 2199
  eng/common/scripts/stress-testing/deploy-stress-tests.ps1
  eng/common/scripts/stress-testing/find-all-stress-packages.ps1
Labels: EngSys, Central-EngSys

#922 Sync eng/common directory with azure-sdk-tools for PR 2202
  eng/common/scripts/ChangeLog-Operations.ps1
  eng/common/scripts/Prepare-Release.ps1
Labels: EngSys, Central-EngSys

#924 Sync eng/common directory with azure-sdk-tools for PR 2219
  eng/common/testproxy/docker-start-proxy.ps1
  eng/common/testproxy/test-proxy-docker.yml
Labels: EngSys, Central-EngSys

#925 Prepare Azure Core for beta release for November 2021
  sdk/core/azure-core-credential/CHANGELOG.md
  sdk/core/azure-core-http-httpurlconnection/CHANGELOG.md
  sdk/core/azure-core-http-okhttp/CHANGELOG.md
  sdk/core/azure-core-http/CHANGELOG.md
  sdk/core/azure-core-jackson/CHANGELOG.md
  sdk/core/azure-core-logging/CHANGELOG.md
  sdk/core/azure-core-rest/CHANGELOG.md
  sdk/core/azure-core-test/CHANGELOG.md
  sdk/core/azure-core/CHANGELOG.md
Labels: Azure.Core

#926 Updated Azure Core versions after releasing a beta version for November 2021.
  build.gradle
  sdk/core/azure-core-credential/gradle.properties
  sdk/core/azure-core-http-httpurlconnection/gradle.properties
  sdk/core/azure-core-http-okhttp/gradle.properties
  sdk/core/azure-core-http/gradle.properties
  sdk/core/azure-core-jackson/gradle.properties
  sdk/core/azure-core-logging/gradle.properties
  sdk/core/azure-core-rest/gradle.properties
  sdk/core/azure-core-test/gradle.properties
  sdk/core/azure-core/gradle.properties
Labels: Azure.Core

#927 Sync eng/common directory with azure-sdk-tools for PR 2223
  eng/common/scripts/stress-testing/deploy-stress-tests.ps1
  eng/common/scripts/stress-testing/find-all-stress-packages.ps1
Labels: EngSys, Central-EngSys

#930 Sync eng/common directory with azure-sdk-tools for PR 2240
  eng/common/scripts/get-codeowners.ps1
Labels: EngSys, Central-EngSys

#931 Sync eng/common directory with azure-sdk-tools for PR 2242
  eng/common/testproxy/test-proxy-tool.yml
Labels: EngSys, Central-EngSys

#932 Sync eng/common directory with azure-sdk-tools for PR 2249
  eng/common/testproxy/test-proxy-docker.yml
  eng/common/testproxy/test-proxy-tool.yml
Labels: EngSys, Central-EngSys

#933 Sync eng/common directory with azure-sdk-tools for PR 2247
  eng/common/TestResources/New-TestResources.ps1
  eng/common/TestResources/clouds/AzureChinaCloud.json
  eng/common/TestResources/clouds/AzureCloud.json
  eng/common/TestResources/clouds/AzureUSGovernment.json
Labels: EngSys, Central-EngSys

#923 Enable encryption for push notification
  sdk/communication/azure-communication-chat/env-prod.properties
  sdk/communication/azure-communication-chat/env-test.properties
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/implementation/notifications/NotificationUtils.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/implementation/notifications/fcm/PushNotificationClient.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/implementation/notifications/fcm/RegistrarClient.java
  sdk/communication/azure-communication-chat/src/test/java/com/azure/android/communication/chat/implementation/notification/NotificationUtilsTest.java
Labels: Communication

#934 Sync eng/common directory with azure-sdk-tools for PR 2259
  eng/common/testproxy/test-proxy-tool.yml
Labels: EngSys, Central-EngSys

#935 Updates to Build System
  build.gradle
  eng/pipelines/aggregate-reports.yml
  eng/pipelines/templates/jobs/archetype-sdk-client.yml
  eng/pipelines/templates/variables/globals.yml
Labels: EngSys

#936 Sync eng/common directory with azure-sdk-tools for PR 2265
  eng/common/scripts/Verify-Links.ps1
Labels: EngSys, Central-EngSys

#937 Sync eng/common directory with azure-sdk-tools for PR 2276
  eng/common/pipelines/templates/jobs/archetype-sdk-tests-generate.yml
Labels: EngSys, Central-EngSys

#938 Update for ACS Chat Android SDK 1.1.0-beta.4 release
  sdk/communication/azure-communication-chat/CHANGELOG.md
Labels: Communication

#939 Sync eng/common directory with azure-sdk-tools for PR 2267
  eng/common/scripts/Prepare-Release.ps1
Labels: EngSys, Central-EngSys

#940 Sync eng/common directory with azure-sdk-tools for PR 2272
  eng/common/scripts/Helpers/Resource-Helpers.ps1
Labels: EngSys, Central-EngSys

#941 Sync eng/common directory with azure-sdk-tools for PR 2290
  eng/common/testproxy/docker-start-proxy.ps1
  eng/common/testproxy/test-proxy-tool.yml
Labels: EngSys, Central-EngSys

#942 Update ACS Chat SDK version after release
  samples/sample-chat-app/src/main/java/com/azure/android/communication/chat/sampleapp/MainActivity.java
  sdk/communication/azure-communication-chat/CHANGELOG.md
  sdk/communication/azure-communication-chat/gradle.properties
Labels: Communication

#944 Sync eng/common directory with azure-sdk-tools for PR 2321
  eng/common/testproxy/docker-start-proxy.ps1
  eng/common/testproxy/test-proxy-tool.yml
Labels: EngSys, Central-EngSys

#945 Sync eng/common directory with azure-sdk-tools for PR 2306
  eng/common/scripts/Helpers/Resource-Helpers.ps1
Labels: EngSys, Central-EngSys

#946 Sync eng/common directory with azure-sdk-tools for PR 2322
  eng/common/scripts/get-codeowners.ps1
Labels: EngSys, Central-EngSys

#947 Sync eng/common directory with azure-sdk-tools for PR 2333
  eng/common/testproxy/docker-start-proxy.ps1
Labels: EngSys, Central-EngSys

#949 Sync eng/common directory with azure-sdk-tools for PR 2086
  eng/common/pipelines/templates/steps/get-pr-owners.yml
  eng/common/scripts/Update-DocsMsMetadata.ps1
  eng/common/scripts/get-codeowners.ps1
Labels: EngSys, Central-EngSys

#954 Sync eng/common directory with azure-sdk-tools for PR 2348
  eng/common/scripts/get-codeowners.ps1
Labels: EngSys, Central-EngSys

#953 Sync eng/common directory with azure-sdk-tools for PR 2331
  eng/common/scripts/stress-testing/deploy-stress-tests.ps1
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys
