Repository Azure/azure-sdk-for-android, pull requests merged in 2021-01, with the labels that each got.

#505 [Communication]: Add teams user identifier
  sdk/communication/azure-communication-common/src/main/java/com/azure/android/communication/common/MicrosoftTeamsUserIdentifier.java
Labels: Communication

#504 Sync eng/common directory with azure-sdk-tools for PR 1299
  eng/common/scripts/Update-ChangeLog.ps1
Labels: Central-EngSys, EngSys

#507 Sync eng/common directory with azure-sdk-tools for PR 1278
  eng/common/scripts/Helpers/DevOps-WorkItem-Helpers.ps1
  eng/common/scripts/SemVer.ps1
  eng/common/scripts/Update-DevOps-Release-WorkItem.ps1
Labels: Central-EngSys, EngSys

#506 Sync eng/common directory with azure-sdk-tools for PR 1298
  eng/common/scripts/copy-docs-to-blobstorage.ps1
Labels: Central-EngSys, EngSys

#509 Sync eng/common directory with azure-sdk-tools for PR 1302
  eng/common/scripts/Verify-Links.ps1
Labels: Central-EngSys, EngSys

#508 Sync eng/common directory with azure-sdk-tools for PR 1301
  eng/common/Update-Change-Log.ps1
  eng/common/scripts/Update-ChangeLog.ps1
Labels: Central-EngSys, EngSys

#510 Sync eng/common directory with azure-sdk-tools for PR 1306
  eng/common/scripts/update-docs-ci.ps1
  eng/common/scripts/update-docs-metadata.ps1
Labels: Central-EngSys, EngSys

#512 Sync eng/common directory with azure-sdk-tools for PR 1308
  eng/common/Update-Change-Log.ps1
  eng/common/scripts/Update-ChangeLog.ps1
Labels: Central-EngSys, EngSys

#513 Sync eng/common directory with azure-sdk-tools for PR 1304
  eng/common/pipelines/templates/steps/prepare-pipelines.yml
Labels: Central-EngSys, EngSys

#514 Sync eng/common directory with azure-sdk-tools for PR 1304
  eng/common/pipelines/templates/steps/prepare-pipelines.yml
Labels: Central-EngSys, EngSys

#516 Sync eng/common directory with azure-sdk-tools for PR 1314
  eng/common/pipelines/templates/steps/install-pipeline-generation.yml
Labels: Central-EngSys, EngSys

#515 [Communication]: Regenerate Chat SDK
  sdk/communication/azure-communication-chat/CHANGELOG.md
  sdk/communication/azure-communication-chat/README.md
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/ChatAsyncClient.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/ChatClient.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/ChatThreadAsyncClient.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/ChatThreadClient.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/implementation/AzureCommunicationChatServiceImpl.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/implementation/ChatThreadsImpl.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/implementation/ChatsImpl.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/AddChatParticipantsErrors.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/AddChatParticipantsResult.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/ChatMessage.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/ChatMessageContent.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/ChatMessagePriority.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/ChatMessageReadReceipt.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/ChatMessageReadReceiptsCollection.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/ChatMessageType.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/ChatMessagesCollection.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/ChatParticipant.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/ChatParticipantsCollection.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/ChatThread.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/ChatThreadInfo.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/ChatThreadsInfoCollection.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/CreateChatThreadResult.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/SendChatMessageRequest.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/SendChatMessageResult.java
  sdk/communication/azure-communication-chat/src/test/java/com/azure/android/communication/chat/MessagesMocker.java
Labels: Communication

#511 Added Core Options types: ClientOptions, RequestOptions and TransportOptions
  sdk/core/azure-core/CHANGELOG.md
  sdk/core/azure-core/src/main/java/com/azure/android/core/http/options/ClientOptions.java
  sdk/core/azure-core/src/main/java/com/azure/android/core/http/options/RequestOptions.java
  sdk/core/azure-core/src/main/java/com/azure/android/core/http/options/TelemetryOptions.java
  sdk/core/azure-core/src/main/java/com/azure/android/core/http/options/TransportOptions.java
Labels: Azure.Core, Client

#521 [Communication]: Android - Rename id property
  sdk/communication/azure-communication-common/src/main/java/com/azure/android/communication/common/MicrosoftTeamsUserIdentifier.java
Labels: Communication

#522 Updated Azure Core version in READMEs for the January 2021 release.
  README.md
  sdk/core/azure-core/README.md
Labels: Azure.Core, Docs

#523 Updated the Azure Core version in its build.gradle file and added release date to CHANGELOG
  sdk/core/azure-core/CHANGELOG.md
  sdk/core/azure-core/build.gradle
Labels: Azure.Core, Client, Docs

#532 Sync eng/common directory with azure-sdk-tools for PR 1318
  eng/common/docgeneration/Generate-DocIndex.ps1
  eng/common/scripts/Create-APIReview.ps1
  eng/common/scripts/Package-Properties.ps1
  eng/common/scripts/artifact-metadata-parsing.ps1
  eng/common/scripts/copy-docs-to-blobstorage.ps1
  eng/common/scripts/update-docs-ci.ps1
Labels: Central-EngSys, EngSys

#519 Enable 1ES hosted pools.
  eng/pipelines/templates/jobs/archetype-sdk-client.yml
  eng/pipelines/templates/variables/globals.yml
Labels: Central-EngSys, EngSys

#524 Updated the Azure Core versions after the January 2021 release.
  sdk/communication/azure-communication-chat/build.gradle
  sdk/communication/azure-communication-common/build.gradle
  sdk/core/azure-core/CHANGELOG.md
  sdk/core/azure-core/build.gradle
Labels: Azure.Core, Communication

#534 Sync eng/common directory with azure-sdk-tools for PR 1317
  eng/common/pipelines/templates/steps/get-pr-owners.yml
Labels: Central-EngSys, EngSys

#535 Sync eng/common directory with azure-sdk-tools for PR 1327
  eng/common/pipelines/templates/steps/bypass-local-dns.yml
Labels: Central-EngSys, EngSys

#536 Sync eng/common directory with azure-sdk-tools for PR 1251
  eng/common/docgeneration/Generate-DocIndex.ps1
  eng/common/scripts/Package-Properties.ps1
  eng/common/scripts/Prepare-Release.ps1
  eng/common/scripts/common.ps1
Labels: Central-EngSys, EngSys

#537 Sync eng/common directory with azure-sdk-tools for PR 1335
  eng/common/scripts/ChangeLog-Operations.ps1
  eng/common/scripts/SemVer.ps1
  eng/common/scripts/Update-ChangeLog.ps1
Labels: Central-EngSys, EngSys

#539 Sync eng/common directory with azure-sdk-tools for PR 1343
  eng/common/docgeneration/Generate-DocIndex.ps1
  eng/common/docgeneration/docfx.json
  eng/common/docgeneration/templates/matthews/styles/main.js
Labels: Central-EngSys, EngSys

#538 Update with latest swagger, version 1.0.0-beta.5
  sdk/communication/azure-communication-chat/CHANGELOG.md
  sdk/communication/azure-communication-chat/README.md
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/ChatAsyncClient.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/ChatClient.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/ChatThreadAsyncClient.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/ChatThreadClient.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/implementation/AzureCommunicationChatServiceImpl.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/implementation/ChatThreadsImpl.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/implementation/ChatsImpl.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/AddChatParticipantsErrors.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/ChatMessage.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/ChatMessageContent.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/ChatParticipant.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/CommunicationError.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/CommunicationErrorResponse.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/CommunicationErrorResponseException.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/CreateChatThreadErrors.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/SendChatMessageRequest.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/UpdateChatMessageRequest.java
Labels: Azure.Core, Communication

#541 Sync eng/common directory with azure-sdk-tools for PR 1341
  eng/common/pipelines/templates/steps/verify-links.yml
Labels: Central-EngSys, EngSys

#542 Update for GA, wrap user string id with CommunicationUserIdentifier
  sdk/communication/azure-communication-chat/build.gradle
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/ChatMessage.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/ChatMessageContent.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/ChatMessageReadReceipt.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/ChatParticipant.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/ChatThread.java
Labels: Communication

#540 [Communication]: Update communication common API with new classes
  sdk/communication/azure-communication-common/CHANGELOG.md
  sdk/communication/azure-communication-common/README.md
  sdk/communication/azure-communication-common/build.gradle
  sdk/communication/azure-communication-common/src/main/java/com/azure/android/communication/common/CallingApplicationIdentifier.java
  sdk/communication/azure-communication-common/src/main/java/com/azure/android/communication/common/CommunicationCloudEnvironment.java
  sdk/communication/azure-communication-common/src/main/java/com/azure/android/communication/common/CommunicationCloudEnvironmentModel.java
  sdk/communication/azure-communication-common/src/main/java/com/azure/android/communication/common/CommunicationIdentifier.java
  sdk/communication/azure-communication-common/src/main/java/com/azure/android/communication/common/CommunicationIdentifierKind.java
  sdk/communication/azure-communication-common/src/main/java/com/azure/android/communication/common/CommunicationIdentifierModel.java
  sdk/communication/azure-communication-common/src/main/java/com/azure/android/communication/common/CommunicationIdentifierSerializer.java
  sdk/communication/azure-communication-common/src/main/java/com/azure/android/communication/common/CommunicationTokenCredential.java
  sdk/communication/azure-communication-common/src/main/java/com/azure/android/communication/common/CommunicationUserIdentifier.java
  sdk/communication/azure-communication-common/src/main/java/com/azure/android/communication/common/MicrosoftTeamsUserIdentifier.java
  sdk/communication/azure-communication-common/src/main/java/com/azure/android/communication/common/PhoneNumber.java
  sdk/communication/azure-communication-common/src/main/java/com/azure/android/communication/common/PhoneNumberIdentifier.java
  sdk/communication/azure-communication-common/src/main/java/com/azure/android/communication/common/UnknownIdentifier.java
  sdk/communication/azure-communication-common/src/test/java/com/azure/android/communication/common/CommunicationIdentifierSerializerTests.java
  sdk/communication/azure-communication-common/src/test/java/com/azure/android/communication/common/CommunicationUserCredentialTest.java
  sdk/communication/azure-communication-common/src/test/java/com/azure/android/communication/common/IdentifierSerialzationExceptionTests.java
  sdk/communication/azure-communication-common/src/test/java/com/azure/android/communication/common/TeamsUserIdentifierSerializationTests.java
Labels: Communication

#543 Marc/picking communication api changes
  sdk/communication/azure-communication-common/CHANGELOG.md
  sdk/communication/azure-communication-common/build.gradle
  sdk/communication/azure-communication-common/src/main/java/com/azure/android/communication/common/AutoRefreshUserCredential.java
  sdk/communication/azure-communication-common/src/main/java/com/azure/android/communication/common/CallingApplicationIdentifier.java
  sdk/communication/azure-communication-common/src/main/java/com/azure/android/communication/common/CommunicationCloudEnvironment.java
  sdk/communication/azure-communication-common/src/main/java/com/azure/android/communication/common/CommunicationCloudEnvironmentModel.java
  sdk/communication/azure-communication-common/src/main/java/com/azure/android/communication/common/CommunicationIdentifier.java
  sdk/communication/azure-communication-common/src/main/java/com/azure/android/communication/common/CommunicationIdentifierKind.java
  sdk/communication/azure-communication-common/src/main/java/com/azure/android/communication/common/CommunicationIdentifierModel.java
  sdk/communication/azure-communication-common/src/main/java/com/azure/android/communication/common/CommunicationIdentifierSerializer.java
  sdk/communication/azure-communication-common/src/main/java/com/azure/android/communication/common/CommunicationTokenCredential.java
  sdk/communication/azure-communication-common/src/main/java/com/azure/android/communication/common/CommunicationUserIdentifier.java
  sdk/communication/azure-communication-common/src/main/java/com/azure/android/communication/common/MicrosoftTeamsUserIdentifier.java
  sdk/communication/azure-communication-common/src/main/java/com/azure/android/communication/common/PhoneNumberIdentifier.java
  sdk/communication/azure-communication-common/src/main/java/com/azure/android/communication/common/UnknownIdentifier.java
  sdk/communication/azure-communication-common/src/test/java/com/azure/android/communication/common/CommunicationIdentifierSerializerTests.java
  sdk/communication/azure-communication-common/src/test/java/com/azure/android/communication/common/CommunicationTokenCredentialTest.java
  sdk/communication/azure-communication-common/src/test/java/com/azure/android/communication/common/IdentifierSerialzationExceptionTests.java
  sdk/communication/azure-communication-common/src/test/java/com/azure/android/communication/common/TeamsUserIdentifierSerializationTests.java
Labels: Communication

#544 [Communication] - Prepare Common package for release
  sdk/communication/azure-communication-common/CHANGELOG.md
  sdk/communication/azure-communication-common/README.md
Labels: Communication

#545 Sync eng/common directory with azure-sdk-tools for PR 1345
  eng/common/pipelines/templates/steps/daily-dev-build-variable.yml
  eng/common/scripts/Create-APIReview.ps1
  eng/common/scripts/Package-Properties.ps1
  eng/common/scripts/Save-Package-Properties.ps1
Labels: Central-EngSys, EngSys
