Repository Azure/azure-sdk-for-android, pull requests merged in 2021-06, with the labels that each got.

#783 Sync eng/common directory with azure-sdk-tools for PR 1611
  eng/common/scripts/Helpers/ApiView-Helpers.ps1
  eng/common/scripts/Prepare-Release.ps1
Labels: Central-EngSys, EngSys

#788 Sync eng/common directory with azure-sdk-tools for PR 1658
  eng/common/scripts/Delete-RemoteBranches.ps1
Labels: Central-EngSys, EngSys

#789 Renaming azure.core.util.Context to azure.core.util.RequestContext
  config/checkstyle/checkstyle-suppressions.xml
  eng/code-quality-reports/src/main/java/com/azure/tools/checkstyle/checks/ServiceClientCheck.java
  samples/sample-chat-app/src/main/java/com/azure/android/communication/chat/sampleapp/MainActivity.java
  sdk/communication/azure-communication-chat/CHANGELOG.md
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/ChatAsyncClient.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/ChatClient.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/ChatThreadAsyncClient.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/ChatThreadClient.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/implementation/ChatImpl.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/implementation/ChatThreadImpl.java
  sdk/core/azure-core-http/CHANGELOG.md
  sdk/core/azure-core-http/src/main/java/com/azure/android/core/http/HttpCallDispatcher.java
  sdk/core/azure-core-http/src/main/java/com/azure/android/core/http/HttpPipeline.java
  sdk/core/azure-core-http/src/main/java/com/azure/android/core/http/HttpPipelinePolicyChain.java
  sdk/core/azure-core-http/src/main/java/com/azure/android/core/http/HttpPipelinePolicyChainImpl.java
  sdk/core/azure-core-http/src/main/java/com/azure/android/core/http/policy/HttpLoggingPolicy.java
  sdk/core/azure-core-http/src/test/java/com/azure/android/core/http/policy/AddHeadersPolicyTest.java
  sdk/core/azure-core-http/src/test/java/com/azure/android/core/http/policy/HostPolicyTests.java
  sdk/core/azure-core-http/src/test/java/com/azure/android/core/http/policy/HttpLoggingPolicyTests.java
  sdk/core/azure-core-http/src/test/java/com/azure/android/core/http/policy/ProtocolPolicyTests.java
  sdk/core/azure-core-http/src/test/java/com/azure/android/core/http/policy/RequestIdPolicyTests.java
  sdk/core/azure-core-http/src/test/java/com/azure/android/core/http/policy/RetryPolicyTests.java
  sdk/core/azure-core-http/src/test/java/com/azure/android/core/http/policy/UserAgentPolicyTests.java
  sdk/core/azure-core-rest/CHANGELOG.md
  sdk/core/azure-core-rest/src/main/java/com/azure/android/core/rest/RestProxy.java
  sdk/core/azure-core/CHANGELOG.md
  sdk/core/azure-core/src/main/java/com/azure/android/core/util/RequestContext.java
  sdk/core/azure-core/src/test/java/com/azure/android/core/util/ContextTests.java
Labels: Azure.Core, Communication

#787 Sync eng/common directory with azure-sdk-tools for PR 1645
  eng/common/scripts/git-branch-push.ps1
Labels: Central-EngSys, EngSys

#790 Sync eng/common directory with azure-sdk-tools for PR 1654
  eng/common/pipelines/templates/jobs/archetype-sdk-tests-generate.yml
Labels: Central-EngSys, EngSys

#791 Updated CHANGELOGs and READMEs for Azure Core's release.
  sdk/core/azure-core-credential/CHANGELOG.md
  sdk/core/azure-core-credential/README.md
  sdk/core/azure-core-http-httpurlconnection/CHANGELOG.md
  sdk/core/azure-core-http-httpurlconnection/README.md
  sdk/core/azure-core-http-okhttp/CHANGELOG.md
  sdk/core/azure-core-http-okhttp/README.md
  sdk/core/azure-core-http/CHANGELOG.md
  sdk/core/azure-core-http/README.md
  sdk/core/azure-core-jackson/CHANGELOG.md
  sdk/core/azure-core-jackson/README.md
  sdk/core/azure-core-logging/CHANGELOG.md
  sdk/core/azure-core-logging/README.md
  sdk/core/azure-core-rest/CHANGELOG.md
  sdk/core/azure-core-rest/README.md
  sdk/core/azure-core-test/CHANGELOG.md
  sdk/core/azure-core-test/README.md
  sdk/core/azure-core/CHANGELOG.md
  sdk/core/azure-core/README.md
Labels: Azure.Core

#792 Disable retain runs while sorting out issue with script location.
  eng/pipelines/templates/stages/archetype-android-release.yml
Labels: Central-EngSys, EngSys

#794 Updated Azure Core's versions after June 2021 beta release.
  build.gradle
  sdk/communication/azure-communication-chat/build.gradle
  sdk/communication/azure-communication-common/build.gradle
  sdk/core/azure-core-credential/CHANGELOG.md
  sdk/core/azure-core-credential/build.gradle
  sdk/core/azure-core-http-httpurlconnection/CHANGELOG.md
  sdk/core/azure-core-http-httpurlconnection/build.gradle
  sdk/core/azure-core-http-okhttp/CHANGELOG.md
  sdk/core/azure-core-http-okhttp/build.gradle
  sdk/core/azure-core-http/CHANGELOG.md
  sdk/core/azure-core-http/build.gradle
  sdk/core/azure-core-jackson/CHANGELOG.md
  sdk/core/azure-core-jackson/build.gradle
  sdk/core/azure-core-logging/CHANGELOG.md
  sdk/core/azure-core-logging/build.gradle
  sdk/core/azure-core-rest/CHANGELOG.md
  sdk/core/azure-core-rest/build.gradle
  sdk/core/azure-core-test/CHANGELOG.md
  sdk/core/azure-core-test/build.gradle
  sdk/core/azure-core/CHANGELOG.md
  sdk/core/azure-core/build.gradle
Labels: Azure.Core, Communication

#795 Update CHANGELOG & README for Chat & Common for release
  README.md
  sdk/communication/azure-communication-chat/CHANGELOG.md
  sdk/communication/azure-communication-chat/README.md
  sdk/communication/azure-communication-chat/build.gradle
  sdk/communication/azure-communication-common/CHANGELOG.md
  sdk/communication/azure-communication-common/README.md
  sdk/communication/azure-communication-common/build.gradle
Labels: Communication

#798 Sync eng/common directory with azure-sdk-tools for PR 1685
  eng/common/scripts/ChangeLog-Operations.ps1
  eng/common/scripts/Update-ChangeLog.ps1
  eng/common/scripts/Verify-ChangeLog.ps1
Labels: Central-EngSys, EngSys

#796 Fix issue in APIView feedback
  samples/sample-chat-app/src/main/java/com/azure/android/communication/chat/sampleapp/MainActivity.java
  sdk/communication/azure-communication-chat/CHANGELOG.md
  sdk/communication/azure-communication-chat/README.md
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/ChatAsyncClient.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/ChatClient.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/ChatClientBuilder.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/ChatThreadAsyncClient.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/ChatThreadClient.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/ChatThreadClientBuilder.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/implementation/converters/AddChatParticipantsResultConverter.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/implementation/converters/ChatErrorConverter.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/implementation/signaling/CommunicationListener.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/implementation/signaling/CommunicationSignalingClient.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/implementation/signaling/EventAccessorHelper.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/implementation/signaling/SignalingClient.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/implementation/signaling/TrouterUtils.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/AddChatParticipantsResult.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/ChatError.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/ChatEvent.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/ChatEventType.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/ChatThreadCreatedEvent.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/ChatThreadEvent.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/ChatThreadPropertiesUpdatedEvent.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/ChatUserEvent.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/RealTimeNotificationCallback.java
  sdk/communication/azure-communication-chat/src/samples/java/com/azure/android/communication/chat/ReadmeSamples.java
  sdk/communication/azure-communication-chat/src/test/java/android/util/Base64.java
  sdk/communication/azure-communication-chat/src/test/java/com/azure/android/communication/chat/ChatAsyncClientTest.java
  sdk/communication/azure-communication-chat/src/test/java/com/azure/android/communication/chat/ChatClientTestBase.java
  sdk/communication/azure-communication-common/CHANGELOG.md
Labels: Communication

#800 Sync eng/common directory with azure-sdk-tools for PR 1688
  eng/common/scripts/ChangeLog-Operations.ps1
Labels: Central-EngSys, EngSys

#801 Update Chat & Common version after release
  sdk/communication/azure-communication-chat/CHANGELOG.md
  sdk/communication/azure-communication-chat/build.gradle
  sdk/communication/azure-communication-common/CHANGELOG.md
  sdk/communication/azure-communication-common/build.gradle
Labels: Communication

#802 Add main to CI files.
  sdk/communication/ci.yml
  sdk/core/ci.yml
Labels: Azure.Core, Communication

#803 Sync eng/common directory with azure-sdk-tools for PR 1711
  eng/common/pipelines/templates/steps/set-default-branch.yml
  eng/common/scripts/update-docs-metadata.ps1
Labels: Central-EngSys, EngSys

#805 Sync eng/common directory with azure-sdk-tools for PR 1716
  eng/common/README.md
  eng/common/docgeneration/Generate-DocIndex.ps1
  eng/common/pipelines/templates/steps/check-spelling.yml
  eng/common/pipelines/templates/steps/docs-metadata-release.yml
  eng/common/pipelines/templates/steps/eng-common-workflow-enforcer.yml
  eng/common/scripts/Create-APIReview.ps1
  eng/common/scripts/Package-Properties.ps1
  eng/common/scripts/Prepare-Release.ps1
  eng/common/scripts/Update-DocsMsPackages.ps1
  eng/common/scripts/artifact-metadata-parsing.ps1
  eng/common/scripts/copy-docs-to-blobstorage.ps1
Labels: Central-EngSys, EngSys

#806 Sync eng/common directory with azure-sdk-tools for PR 1719
  eng/common/pipelines/templates/steps/install-pipeline-generation.yml
Labels: Central-EngSys, EngSys

#807 Sync eng/common directory with azure-sdk-tools for PR 1729
  eng/common/scripts/Create-APIReview.ps1
  eng/common/scripts/Package-Properties.ps1
  eng/common/scripts/Save-Package-Properties.ps1
Labels: Central-EngSys, EngSys

#808 Sync eng/common directory with azure-sdk-tools for PR 1736
  eng/common/pipelines/templates/steps/bypass-local-dns.yml
Labels: Central-EngSys, EngSys

#810 Sync eng/common directory with azure-sdk-tools for PR 1739
  eng/common/scripts/Verify-Links.ps1
  eng/common/scripts/update-docs-metadata.ps1
Labels: Central-EngSys, EngSys

#809 Update master to main
  .github/CODEOWNERS
  CONTRIBUTING.md
  README.md
  doc/README.md
  eng/code-quality-reports/src/main/resources/index.html
  sdk/communication/azure-communication-chat/CHANGELOG.md
  sdk/communication/azure-communication-chat/README.md
  sdk/communication/azure-communication-common/CHANGELOG.md
  sdk/communication/azure-communication-common/README.md
  sdk/communication/ci.yml
  sdk/core/README.md
  sdk/core/ci.yml
Labels: Azure.Core, Communication

#812 Sync eng/common directory with azure-sdk-tools for PR 1725
  eng/common/pipelines/templates/steps/enable-long-path-support.yml
  eng/common/pipelines/templates/steps/set-daily-docs-branch-name.yml
  eng/common/pipelines/templates/steps/set-default-branch.yml
  eng/common/pipelines/templates/steps/update-docsms-metadata.yml
  eng/common/scripts/Invoke-DevOpsAPI.ps1
  eng/common/scripts/Package-Properties.ps1
  eng/common/scripts/Queue-Pipeline.ps1
  eng/common/scripts/Save-Package-Properties.ps1
  eng/common/scripts/Update-DocsMsMetadata.ps1
  eng/common/scripts/Update-DocsMsPackages.ps1
  eng/common/scripts/common.ps1
Labels: Central-EngSys, EngSys

#813 Sync eng/common directory with azure-sdk-tools for PR 1759
  eng/common/scripts/Helpers/DevOps-WorkItem-Helpers.ps1
Labels: Central-EngSys, EngSys

#814 Sync eng/common directory with azure-sdk-tools for PR 1763
  eng/common/scripts/Package-Properties.ps1
Labels: Central-EngSys, EngSys
