Repository Azure/azure-sdk-for-android, pull requests merged in 2021-02, with the labels that each got.

#549 Sync eng/common directory with azure-sdk-tools for PR 1351
  eng/common/TestResources/README.md
Labels: Central-EngSys, EngSys

#550 Sync eng/common directory with azure-sdk-tools for PR 1361
  eng/common/scripts/Prepare-Release.ps1
Labels: Central-EngSys, EngSys

#551 Sync eng/common directory with azure-sdk-tools for PR 1353
  eng/common/scripts/artifact-metadata-parsing.ps1
  eng/common/scripts/update-docs-metadata.ps1
Labels: Central-EngSys, EngSys

#554 Sync eng/common directory with azure-sdk-tools for PR 1364
  eng/common/scripts/Create-APIReview.ps1
  eng/common/scripts/Save-Package-Properties.ps1
Labels: Central-EngSys, EngSys

#555 Sync eng/common directory with azure-sdk-tools for PR 1365
  eng/common/pipelines/templates/steps/cosmos-emulator.yml
Labels: Central-EngSys, EngSys

#553 [Communication]: Update release version number in gradle, readme, and changelog
  sdk/communication/azure-communication-common/CHANGELOG.md
  sdk/communication/azure-communication-common/README.md
  sdk/communication/azure-communication-common/build.gradle
Labels: Communication

#556 Sync eng/common directory with azure-sdk-tools for PR 1366
  eng/common/docgeneration/Generate-DocIndex.ps1
Labels: Central-EngSys, EngSys

#557 [Communication]: Identifier serializer update for new model
  sdk/communication/azure-communication-common/src/main/java/com/azure/android/communication/common/CallingApplicationIdentifier.java
  sdk/communication/azure-communication-common/src/main/java/com/azure/android/communication/common/CommunicationCloudEnvironment.java
  sdk/communication/azure-communication-common/src/main/java/com/azure/android/communication/common/CommunicationCloudEnvironmentModel.java
  sdk/communication/azure-communication-common/src/main/java/com/azure/android/communication/common/CommunicationIdentifier.java
  sdk/communication/azure-communication-common/src/main/java/com/azure/android/communication/common/CommunicationIdentifierKind.java
  sdk/communication/azure-communication-common/src/main/java/com/azure/android/communication/common/CommunicationIdentifierModel.java
  sdk/communication/azure-communication-common/src/main/java/com/azure/android/communication/common/CommunicationIdentifierSerializer.java
  sdk/communication/azure-communication-common/src/main/java/com/azure/android/communication/common/CommunicationUserIdentifier.java
  sdk/communication/azure-communication-common/src/main/java/com/azure/android/communication/common/CommunicationUserIdentifierModel.java
  sdk/communication/azure-communication-common/src/main/java/com/azure/android/communication/common/MicrosoftTeamsUserIdentifier.java
  sdk/communication/azure-communication-common/src/main/java/com/azure/android/communication/common/MicrosoftTeamsUserIdentifierModel.java
  sdk/communication/azure-communication-common/src/main/java/com/azure/android/communication/common/PhoneNumberIdentifier.java
  sdk/communication/azure-communication-common/src/main/java/com/azure/android/communication/common/PhoneNumberIdentifierModel.java
  sdk/communication/azure-communication-common/src/main/java/com/azure/android/communication/common/UnknownIdentifier.java
  sdk/communication/azure-communication-common/src/test/java/com/azure/android/communication/common/CommunicationIdentifierSerializerTests.java
  sdk/communication/azure-communication-common/src/test/java/com/azure/android/communication/common/IdentifierDeserializationExceptionTests.java
  sdk/communication/azure-communication-common/src/test/java/com/azure/android/communication/common/IdentifierSerialzationExceptionTests.java
  sdk/communication/azure-communication-common/src/test/java/com/azure/android/communication/common/TeamsUserIdentifierSerializationTests.java
Labels: Communication

#560 Sync eng/common directory with azure-sdk-tools for PR 1376
  eng/common/scripts/Helpers/DevOps-WorkItem-Helpers.ps1
  eng/common/scripts/SemVer.ps1
Labels: Central-EngSys, EngSys

#558 [Communication] Update files for February release
  sdk/communication/azure-communication-chat/CHANGELOG.md
  sdk/communication/azure-communication-common/CHANGELOG.md
  sdk/communication/azure-communication-common/src/main/java/com/azure/android/communication/common/MicrosoftTeamsUserIdentifier.java
Labels: Communication

#562 Update readme, changelog, add back some previous changes
  sdk/communication/azure-communication-chat/CHANGELOG.md
  sdk/communication/azure-communication-chat/README.md
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/ChatThreadAsyncClient.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/ChatThreadClient.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/implementation/ChatThreadsImpl.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/UpdateTopicRequest.java
Labels: Communication

#564 [Communication]: Update build.gradle and ChangeLog for common and Chat after release
  sdk/communication/azure-communication-chat/CHANGELOG.md
  sdk/communication/azure-communication-chat/build.gradle
  sdk/communication/azure-communication-common/CHANGELOG.md
  sdk/communication/azure-communication-common/build.gradle
Labels: Communication

#566 Sync eng/common directory with azure-sdk-tools for PR 1393
  eng/common/docgeneration/Generate-DocIndex.ps1
Labels: Central-EngSys, EngSys

#568 Cleaning up dependencies section in build.gradle files
  sdk/core/azure-core-credential/build.gradle
  sdk/core/azure-core-customserde/build.gradle
  sdk/core/azure-core-http-httpurlconnection/build.gradle
  sdk/core/azure-core-http-okhttp/build.gradle
  sdk/core/azure-core-http-okhttp/src/samples/java/com/azure/core/http/okhttp/OkHttpAsyncHttpClientBuilderJavaDocCodeSnippets.java
  sdk/core/azure-core-http-okhttp/src/samples/java/com/azure/core/http/okhttp/ReadmeSamples.java
  sdk/core/azure-core-http/build.gradle
  sdk/core/azure-core-http/src/main/java/com/azure/android/core/http/HttpPipelineBuilder.java
  sdk/core/azure-core-rest/build.gradle
  sdk/core/azure-core-serde-jackson/build.gradle
  sdk/core/azure-core-test/build.gradle
  sdk/core/azure-core-test/src/main/java/com/azure/android/core/test/http/PlaybackClient.java
  sdk/core/azure-core-test/src/main/java/com/azure/android/core/test/policy/RecordNetworkCallPolicy.java
  sdk/core/azure-core-test/src/samples/java/com/azure/core/test/ReadmeSamples.java
  sdk/core/azure-core/build.gradle
Labels: Azure.Core

#569 Sync eng/common directory with azure-sdk-tools for PR 1303
  eng/common/scripts/Collect-ChangeLogs.ps1
Labels: Central-EngSys, EngSys

#570 Updating logging module compatible to api-level 14 & remove duplicate method with a typo in the name.
  sdk/core/azure-core-logging/src/main/java/com/azure/android/core/logging/ClientLogger.java
Labels: Azure.Core

#571 Sync eng/common directory with azure-sdk-tools for PR 1358
  eng/common/pipelines/templates/steps/eng-common-workflow-enforcer.yml
Labels: Central-EngSys, EngSys

#572 Updating serde contract module to use min api as 14
  sdk/core/azure-core-serde/src/main/java/com/azure/android/core/serde/SerdeAdapter.java
Labels: Azure.Core

#573 Sync eng/common directory with azure-sdk-tools for PR 1386
  eng/common/scripts/Helpers/DevOps-WorkItem-Helpers.ps1
  eng/common/scripts/Update-DevOps-Release-WorkItem.ps1
Labels: Central-EngSys, EngSys

#574 Sync eng/common directory with azure-sdk-tools for PR 1307
  eng/common/scripts/Update-ChangeLog.ps1
Labels: Central-EngSys, EngSys

#575 Sync eng/common directory with azure-sdk-tools for PR 1401
  eng/common/pipelines/templates/steps/eng-common-workflow-enforcer.yml
Labels: Central-EngSys, EngSys

#576 Sync eng/common directory with azure-sdk-tools for PR 1405
  eng/common/TestResources/New-TestResources.ps1
  eng/common/TestResources/New-TestResources.ps1.md
Labels: Central-EngSys, EngSys

#577 [Communication] - Chat - Generating Identifier Models
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/CommunicationIdentifierSerializer.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/ChatParticipant.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/CommunicationCloudEnvironmentModel.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/CommunicationIdentifierModel.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/CommunicationUserIdentifierModel.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/MicrosoftTeamsUserIdentifierModel.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/PhoneNumberIdentifierModel.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/package-info.java
  sdk/communication/azure-communication-chat/src/test/java/com/azure/android/communication/chat/CommunicationIdentifierSerializerTests.java
  sdk/communication/azure-communication-chat/swagger/README.md
  sdk/communication/azure-communication-chat/swagger/swagger.json
  sdk/communication/azure-communication-common/src/main/java/com/azure/android/communication/common/CommunicationCloudEnvironment.java
Labels: Communication

#578 Sync eng/common directory with azure-sdk-tools for PR 1408
  eng/common/TestResources/New-TestResources.ps1
  eng/common/TestResources/README.md
Labels: Central-EngSys, EngSys

#563 Sync eng/common directory with azure-sdk-tools for PR 1371
  eng/common/pipelines/templates/steps/verify-agent-os.yml
  eng/common/scripts/Verify-AgentOS.ps1
Labels: Central-EngSys, EngSys

#559 Re-enable OS image verification
  eng/pipelines/templates/jobs/archetype-sdk-client.yml
  eng/pipelines/templates/variables/globals.yml
Labels: Central-EngSys, EngSys

#579 Sync eng/common directory with azure-sdk-tools for PR 1374
  eng/common/pipelines/templates/steps/create-apireview.yml
  eng/common/scripts/Package-Properties.ps1
  eng/common/scripts/Save-Package-Properties.ps1
Labels: Central-EngSys, EngSys

#580 [Communication] - Common - Rename token to initialToken
  sdk/communication/azure-communication-common/src/main/java/com/azure/android/communication/common/CommunicationTokenRefreshOptions.java
Labels: Communication

#583 Sync eng/common directory with azure-sdk-tools for PR 1396
  eng/common/docgeneration/templates/matthews/styles/main.js
Labels: Central-EngSys, EngSys

#584 [Communication] - Common - Update CommunicationTokenCredential ctor to use CommunicationTokenRefreshOptions
  sdk/communication/azure-communication-common/CHANGELOG.md
  sdk/communication/azure-communication-common/README.md
  sdk/communication/azure-communication-common/src/main/java/com/azure/android/communication/common/CommunicationTokenCredential.java
  sdk/communication/azure-communication-common/src/test/java/com/azure/android/communication/common/CommunicationTokenCredentialTest.java
Labels: Communication

#581 Sync eng/common directory with azure-sdk-tools for PR 1415
  eng/common/pipelines/templates/steps/eng-common-workflow-enforcer.yml
Labels: Central-EngSys, EngSys

#586 Sync eng/common directory with azure-sdk-tools for PR 1425
  eng/common/scripts/get-markdown-files-from-changed-files.ps1
Labels: Central-EngSys, EngSys

#591 Replacing java8-only java.time with Time types from 310bp
  config/checkstyle/checkstyle-suppressions.xml
  config/spotbugs/spotbugs-exclude.xml
  sdk/core/azure-core-credential/build.gradle
  sdk/core/azure-core-credential/src/main/java/com/azure/android/core/credential/AccessToken.java
  sdk/core/azure-core-http/src/main/java/com/azure/android/core/http/policy/AddDatePolicy.java
  sdk/core/azure-core-http/src/main/java/com/azure/android/core/http/policy/ExponentialBackoff.java
  sdk/core/azure-core-http/src/main/java/com/azure/android/core/http/policy/FixedDelay.java
  sdk/core/azure-core-http/src/main/java/com/azure/android/core/http/policy/RetryPolicy.java
  sdk/core/azure-core-http/src/main/java/com/azure/android/core/http/policy/RetryStrategy.java
  sdk/core/azure-core-http/src/test/java/com/azure/android/core/http/policy/ExponentialBackoffTest.java
  sdk/core/azure-core-http/src/test/java/com/azure/android/core/http/policy/FixedDelayTest.java
  sdk/core/azure-core-http/src/test/java/com/azure/android/core/http/policy/RequestIdPolicyTests.java
  sdk/core/azure-core-http/src/test/java/com/azure/android/core/http/policy/RetryPolicyTests.java
  sdk/core/azure-core-rest/src/main/java/com/azure/android/core/rest/HttpResponseMapper.java
  sdk/core/azure-core-rest/src/test/java/com/azure/android/core/rest/HttpRequestMapperTests.java
  sdk/core/azure-core-rest/src/test/java/com/azure/android/core/rest/HttpResponseMapperTests.java
  sdk/core/azure-core-rest/src/test/java/com/azure/android/core/rest/RestProxyXMLTests.java
  sdk/core/azure-core-serde-jackson/src/main/java/com/azure/android/core/serde/jackson/AccessibleByteArrayOutputStream.java
  sdk/core/azure-core-serde-jackson/src/main/java/com/azure/android/core/serde/jackson/DateTimeDeserializer.java
  sdk/core/azure-core-serde-jackson/src/main/java/com/azure/android/core/serde/jackson/DateTimeSerializer.java
  sdk/core/azure-core-serde-jackson/src/main/java/com/azure/android/core/serde/jackson/DurationSerializer.java
  sdk/core/azure-core-serde-jackson/src/main/java/com/azure/android/core/serde/jackson/FlatteningSerializer.java
  sdk/core/azure-core-serde-jackson/src/main/java/com/azure/android/core/serde/jackson/JacksonSerderAdapter.java
  sdk/core/azure-core-serde-jackson/src/main/java/com/azure/android/core/serde/jackson/implementation/package-info.java
  sdk/core/azure-core-serde-jackson/src/main/java/com/azure/android/core/serde/jackson/implementation/threeten/BiFunction.java
  sdk/core/azure-core-serde-jackson/src/main/java/com/azure/android/core/serde/jackson/implementation/threeten/DecimalUtils.java
  sdk/core/azure-core-serde-jackson/src/main/java/com/azure/android/core/serde/jackson/implementation/threeten/DurationDeserializer.java
  sdk/core/azure-core-serde-jackson/src/main/java/com/azure/android/core/serde/jackson/implementation/threeten/DurationSerializer.java
  sdk/core/azure-core-serde-jackson/src/main/java/com/azure/android/core/serde/jackson/implementation/threeten/Function.java
  sdk/core/azure-core-serde-jackson/src/main/java/com/azure/android/core/serde/jackson/implementation/threeten/InstantDeserializer.java
  sdk/core/azure-core-serde-jackson/src/main/java/com/azure/android/core/serde/jackson/implementation/threeten/InstantSerializerBase.java
  sdk/core/azure-core-serde-jackson/src/main/java/com/azure/android/core/serde/jackson/implementation/threeten/OffsetDateTimeSerializer.java
  sdk/core/azure-core-serde-jackson/src/main/java/com/azure/android/core/serde/jackson/implementation/threeten/ThreeTenDateTimeDeserializerBase.java
  sdk/core/azure-core-serde-jackson/src/main/java/com/azure/android/core/serde/jackson/implementation/threeten/ThreeTenDeserializerBase.java
  sdk/core/azure-core-serde-jackson/src/main/java/com/azure/android/core/serde/jackson/implementation/threeten/ThreeTenFormattedSerializerBase.java
  sdk/core/azure-core-serde-jackson/src/main/java/com/azure/android/core/serde/jackson/implementation/threeten/ThreeTenModule.java
  sdk/core/azure-core-serde-jackson/src/main/java/com/azure/android/core/serde/jackson/implementation/threeten/ThreeTenSerializerBase.java
  sdk/core/azure-core-serde-jackson/src/main/java/com/azure/android/core/serde/jackson/implementation/threeten/ToIntFunction.java
  sdk/core/azure-core-serde-jackson/src/main/java/com/azure/android/core/serde/jackson/implementation/threeten/ToLongFunction.java
  sdk/core/azure-core-serde-jackson/src/main/java/com/azure/android/core/serde/jackson/implementation/threeten/package-info.java
  sdk/core/azure-core-serde-jackson/src/test/java/com/azure/android/core/serde/jackson/AccessPolicy.java
  sdk/core/azure-core-serde-jackson/src/test/java/com/azure/android/core/serde/jackson/DateTimeDeserializerTests.java
  sdk/core/azure-core-serde-jackson/src/test/java/com/azure/android/core/serde/jackson/DateTimeSerializerTests.java
  sdk/core/azure-core-serde-jackson/src/test/java/com/azure/android/core/serde/jackson/DurationSerializerTests.java
  sdk/core/azure-core-serde-jackson/src/test/java/com/azure/android/core/serde/jackson/JacksonSerderAdapterTests.java
  sdk/core/azure-core-test/src/main/java/com/azure/android/core/test/RestProxyTestsWireMockServer.java
  sdk/core/azure-core-test/src/main/java/com/azure/android/core/test/http/MockHttpClient.java
  sdk/core/azure-core-test/src/main/java/com/azure/android/core/test/implementation/entities/AccessPolicy.java
  sdk/core/azure-core-test/src/main/java/com/azure/android/core/test/utils/TestResourceNamer.java
  sdk/core/azure-core/build.gradle
  sdk/core/azure-core/src/main/java/com/azure/android/core/util/DateTimeRfc1123.java
  sdk/core/azure-core/src/main/java/com/azure/android/core/util/UnixTime.java
Labels: Azure.Core

#587 Sync eng/common directory with azure-sdk-tools for PR 1429
  eng/common/pipelines/templates/jobs/archetype-sdk-tests-generate.yml
  eng/common/scripts/job-matrix/Create-JobMatrix.ps1
  eng/common/scripts/job-matrix/README.md
  eng/common/scripts/job-matrix/job-matrix-functions.ps1
  eng/common/scripts/job-matrix/samples/matrix-job-sample.yml
  eng/common/scripts/job-matrix/samples/matrix-test.yml
  eng/common/scripts/job-matrix/samples/matrix.json
  eng/common/scripts/job-matrix/tests/job-matrix-functions.filter.tests.ps1
  eng/common/scripts/job-matrix/tests/job-matrix-functions.modification.tests.ps1
  eng/common/scripts/job-matrix/tests/job-matrix-functions.tests.ps1
  eng/common/scripts/job-matrix/tests/test-import-matrix.json
Labels: Central-EngSys, EngSys

#592 Sync eng/common directory with azure-sdk-tools for PR 1436
  eng/common/pipelines/templates/steps/install-pipeline-generation.yml
Labels: Central-EngSys, EngSys

#593 Making azure-core module baselined to ApiLevel-15
  build.gradle
  config/checkstyle/checkstyle-suppressions.xml
  sdk/core/azure-core-http/src/main/java/com/azure/android/core/http/exception/HttpRequestException.java
  sdk/core/azure-core-http/src/main/java/com/azure/android/core/http/exception/HttpResponseException.java
  sdk/core/azure-core-rest/src/test/java/android/util/Base64.java
  sdk/core/azure-core/build.gradle
  sdk/core/azure-core/src/androidTest/java/com/azure/android/core/util/Base64UrlTests.java
  sdk/core/azure-core/src/androidTest/java/com/azure/android/core/util/Base64UtilTests.java
  sdk/core/azure-core/src/main/java/com/azure/android/core/exception/AzureException.java
  sdk/core/azure-core/src/main/java/com/azure/android/core/util/Base64Url.java
  sdk/core/azure-core/src/main/java/com/azure/android/core/util/Base64Util.java
  sdk/core/azure-core/src/main/java/com/azure/android/core/util/CancellationToken.java
  sdk/core/azure-core/src/main/java/com/azure/android/core/util/Context.java
  sdk/core/azure-core/src/main/java/com/azure/android/core/util/Header.java
  sdk/core/azure-core/src/main/java/com/azure/android/core/util/Option.java
Labels: Azure.Core

#594 Making azure-core-http and azure-core-credentials modules baselined to ApiLevel-15
  build.gradle
  config/checkstyle/checkstyle-suppressions.xml
  sdk/core/azure-core-credential/build.gradle
  sdk/core/azure-core-credential/src/main/java/com/azure/android/core/credential/AzureKeyCredential.java
  sdk/core/azure-core-credential/src/main/java/com/azure/android/core/credential/TokenRequestContext.java
  sdk/core/azure-core-http/build.gradle
  sdk/core/azure-core-http/src/main/java/com/azure/android/core/http/HttpCallDispatcher.java
  sdk/core/azure-core-http/src/main/java/com/azure/android/core/http/HttpHeaders.java
  sdk/core/azure-core-http/src/main/java/com/azure/android/core/http/HttpPipeline.java
  sdk/core/azure-core-http/src/main/java/com/azure/android/core/http/HttpPipelinePolicyChainImpl.java
  sdk/core/azure-core-http/src/main/java/com/azure/android/core/http/HttpRequest.java
  sdk/core/azure-core-http/src/main/java/com/azure/android/core/http/PolicyCompleter.java
  sdk/core/azure-core-http/src/main/java/com/azure/android/core/http/implementation/BufferedHttpResponse.java
  sdk/core/azure-core-http/src/main/java/com/azure/android/core/http/implementation/Util.java
  sdk/core/azure-core-http/src/main/java/com/azure/android/core/http/policy/AzureKeyCredentialPolicy.java
  sdk/core/azure-core-http/src/main/java/com/azure/android/core/http/policy/BearerTokenAuthenticationPolicy.java
  sdk/core/azure-core-http/src/main/java/com/azure/android/core/http/policy/CookiePolicy.java
  sdk/core/azure-core-http/src/main/java/com/azure/android/core/http/policy/ExponentialBackoff.java
  sdk/core/azure-core-http/src/main/java/com/azure/android/core/http/policy/FixedDelay.java
  sdk/core/azure-core-http/src/main/java/com/azure/android/core/http/policy/HttpLogOptions.java
  sdk/core/azure-core-http/src/main/java/com/azure/android/core/http/policy/HttpLoggingPolicy.java
  sdk/core/azure-core-http/src/main/java/com/azure/android/core/http/policy/RequestIdPolicy.java
  sdk/core/azure-core-http/src/main/java/com/azure/android/core/http/util/AuthorizationChallengeHandler.java
  sdk/core/azure-core-http/src/main/java/com/azure/android/core/http/util/UrlBuilder.java
  sdk/core/azure-core-http/src/test/java/com/azure/android/core/http/policy/AddHeadersPolicyTest.java
  sdk/core/azure-core-http/src/test/java/com/azure/android/core/http/policy/HostPolicyTests.java
  sdk/core/azure-core-http/src/test/java/com/azure/android/core/http/policy/HttpLoggingPolicyTests.java
  sdk/core/azure-core-http/src/test/java/com/azure/android/core/http/policy/MockHttpResponse.java
  sdk/core/azure-core-http/src/test/java/com/azure/android/core/http/policy/NoOpHttpClient.java
  sdk/core/azure-core-http/src/test/java/com/azure/android/core/http/policy/ProtocolPolicyTests.java
  sdk/core/azure-core-http/src/test/java/com/azure/android/core/http/policy/RequestIdPolicyTests.java
  sdk/core/azure-core-http/src/test/java/com/azure/android/core/http/policy/RetryPolicyTests.java
  sdk/core/azure-core-http/src/test/java/com/azure/android/core/http/policy/UserAgentPolicyTests.java
  sdk/core/azure-core-logging/build.gradle
  sdk/core/azure-core-rest/build.gradle
  sdk/core/azure-core-rest/src/test/java/com/azure/android/core/rest/AccessPolicy.java
  sdk/core/azure-core-rest/src/test/java/com/azure/android/core/rest/MockHttpResponse.java
  sdk/core/azure-core-rest/src/test/java/com/azure/android/core/rest/RestProxyXMLTests.java
  sdk/core/azure-core-rest/src/test/java/com/azure/android/core/rest/SignedIdentifierInner.java
  sdk/core/azure-core-rest/src/test/java/com/azure/android/core/rest/SignedIdentifiersWrapper.java
  sdk/core/azure-core-rest/src/test/java/com/azure/android/core/rest/Slide.java
  sdk/core/azure-core-rest/src/test/java/com/azure/android/core/rest/Slideshow.java
  sdk/core/azure-core-test/build.gradle
  sdk/core/azure-core/build.gradle
Labels: Azure.Core

#595 Making azure-core-http-httpurlconnection baselined to apiLevel-15 and azure-core-http-okhttp to apiLevel-21
  config/checkstyle/checkstyle-suppressions.xml
  sdk/core/azure-core-http-httpurlconnection/build.gradle
  sdk/core/azure-core-http-httpurlconnection/src/main/AndroidManifest.xml
  sdk/core/azure-core-http-httpurlconnection/src/main/java/com/azure/android/core/http/httpurlconnection/HttpUrlConnectionAsyncHttpClient.java
  sdk/core/azure-core-http-httpurlconnection/src/main/java/com/azure/android/core/http/httpurlconnection/HttpUrlConnectionAsyncHttpClientBuilder.java
  sdk/core/azure-core-http-okhttp/build.gradle
  sdk/core/azure-core-http-okhttp/src/main/AndroidManifest.xml
  sdk/core/azure-core-serde/build.gradle
Labels: Azure.Core

#596 Making azure-core-serde-jackson, azure-core-custom-(serde|serde-json-jackson) baselined to apiLevel-15
  sdk/core/azure-core-customserde-json-jackson/build.gradle
  sdk/core/azure-core-customserde-json-jackson/src/main/java/com/azure/core/customserde/json/jackson/JacksonJsonSerializer.java
  sdk/core/azure-core-customserde/build.gradle
  sdk/core/azure-core-customserde/src/main/java/com/azure/core/customserde/TypeReference.java
  sdk/core/azure-core-serde-jackson/build.gradle
  sdk/core/azure-core-serde-jackson/src/main/java/com/azure/android/core/serde/jackson/JacksonSerderAdapter.java
  sdk/core/azure-core-serde-jackson/src/main/java/com/azure/android/core/serde/jackson/SerdeJacksonAnnotationIntrospector.java
Labels: Azure.Core

#590 Sync eng/common directory with azure-sdk-tools for PR 1428
  eng/common/pipelines/templates/steps/verify-agent-os.yml
  eng/common/scripts/Verify-AgentOS.ps1
Labels: Central-EngSys, EngSys

#598 Making azure-core-rest module baselined to apiLevel-15
  sdk/core/azure-core-http-httpurlconnection/src/main/AndroidManifest.xml
  sdk/core/azure-core-http-okhttp/src/main/AndroidManifest.xml
  sdk/core/azure-core-rest/build.gradle
  sdk/core/azure-core-rest/src/main/java/com/azure/android/core/rest/HttpResponseMapper.java
  sdk/core/azure-core-rest/src/main/java/com/azure/android/core/rest/PercentEscaper.java
  sdk/core/azure-core-rest/src/main/java/com/azure/android/core/rest/SwaggerMethodParser.java
  sdk/core/azure-core-rest/src/main/java/com/azure/android/core/rest/implementation/HttpResponseExceptionInfo.java
  sdk/core/azure-core-rest/src/main/java/com/azure/android/core/rest/implementation/TypeUtil.java
  sdk/core/azure-core-rest/src/test/java/com/azure/android/core/rest/HttpResponseMapperTests.java
  sdk/core/azure-core-test/src/main/java/com/azure/android/core/test/implementation/RestProxyTests.java
Labels: Azure.Core

#599 Configuring the minSdkVersion to 15 in the project level build.gradle
  build.gradle
  sdk/core/azure-core-credential/build.gradle
  sdk/core/azure-core-customserde-json-jackson/build.gradle
  sdk/core/azure-core-customserde/build.gradle
  sdk/core/azure-core-http-httpurlconnection/build.gradle
  sdk/core/azure-core-http/build.gradle
  sdk/core/azure-core-logging/build.gradle
  sdk/core/azure-core-rest/build.gradle
  sdk/core/azure-core-serde-jackson/build.gradle
  sdk/core/azure-core-serde/build.gradle
  sdk/core/azure-core-test/build.gradle
  sdk/core/azure-core/build.gradle
Labels: Azure.Core

#585 Update README.md
  README.md
  sdk/communication/azure-communication-chat/README.md
Labels: Communication

#597 Sync eng/common directory with azure-sdk-tools for PR 1421
  eng/common/pipelines/templates/steps/check-spelling.yml
  eng/common/scripts/check-spelling-in-changed-files.ps1
Labels: Central-EngSys, EngSys

#582 Run chat preview4 swagger
  README.md
  eng/common/docgeneration/Generate-DocIndex.ps1
  eng/common/pipelines/templates/steps/eng-common-workflow-enforcer.yml
  eng/common/scripts/Collect-ChangeLogs.ps1
  eng/common/scripts/Helpers/DevOps-WorkItem-Helpers.ps1
  eng/common/scripts/Update-ChangeLog.ps1
  eng/common/scripts/Update-DevOps-Release-WorkItem.ps1
  sdk/communication/azure-communication-chat/CHANGELOG.md
  sdk/communication/azure-communication-chat/README.md
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/ChatAsyncClient.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/ChatClient.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/ChatThreadAsyncClient.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/ChatThreadClient.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/CommunicationIdentifierSerializer.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/implementation/AzureCommunicationChatServiceImpl.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/implementation/ChatThreadsImpl.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/implementation/ChatsImpl.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/implementation/package-info.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/ChatMessage.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/ChatMessageContent.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/ChatMessageReadReceipt.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/ChatParticipant.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/ChatThread.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/CommunicationCloudEnvironmentModel.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/CommunicationIdentifierModel.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/CommunicationUserIdentifierModel.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/MicrosoftTeamsUserIdentifierModel.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/PhoneNumberIdentifierModel.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/package-info.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/package-info.java
  sdk/communication/azure-communication-chat/src/test/java/com/azure/android/communication/chat/CommunicationIdentifierSerializerTests.java
  sdk/communication/azure-communication-chat/src/test/java/com/azure/android/communication/chat/IdentifierDeserializationExceptionTests.java
  sdk/communication/azure-communication-chat/src/test/java/com/azure/android/communication/chat/IdentifierSerialzationExceptionTests.java
  sdk/communication/azure-communication-chat/src/test/java/com/azure/android/communication/chat/TeamsUserIdentifierSerializationTests.java
  sdk/communication/azure-communication-chat/swagger/README.md
  sdk/communication/azure-communication-common/src/main/java/com/azure/android/communication/common/CommunicationCloudEnvironment.java
Labels: Communication

#601 Code cleanup in azure-core-jackson module
  sdk/core/azure-core-jackson/build.gradle
  sdk/core/azure-core-jackson/src/main/java/com/azure/android/core/serde/jackson/JacksonSerder.java
  sdk/core/azure-core-jackson/src/main/java/com/azure/android/core/serde/jackson/TypeUtil.java
  sdk/core/azure-core-jackson/src/test/java/com/azure/android/core/serde/jackson/JacksonSerderTests.java
  sdk/core/azure-core-rest/src/main/java/com/azure/android/core/rest/HttpRequestMapper.java
  sdk/core/azure-core-rest/src/main/java/com/azure/android/core/rest/HttpResponseMapper.java
  sdk/core/azure-core-rest/src/main/java/com/azure/android/core/rest/RestProxy.java
  sdk/core/azure-core-rest/src/main/java/com/azure/android/core/rest/SwaggerInterfaceParser.java
  sdk/core/azure-core-rest/src/main/java/com/azure/android/core/rest/SwaggerMethodParser.java
  sdk/core/azure-core-rest/src/main/java/com/azure/android/core/rest/implementation/HttpResponseExceptionInfo.java
  sdk/core/azure-core-rest/src/test/java/com/azure/android/core/rest/HttpResponseMapperTests.java
Labels: Azure.Core

#602 Enable SPI for Http modules
  sdk/core/azure-core-http-httpurlconnection/src/main/java/com/azure/android/core/http/httpurlconnection/HttpUrlConnectionAsyncHttpClientProvider.java
  sdk/core/azure-core-http-httpurlconnection/src/main/resources/META-INF/services/com.azure.core.http.HttpClientProvider
  sdk/core/azure-core-http-okhttp/src/main/java/com/azure/android/core/http/okhttp/OkHttpAsyncClientProvider.java
  sdk/core/azure-core-http-okhttp/src/main/resources/META-INF/services/com.azure.core.http.HttpClientProvider
Labels: Azure.Core

#603 custom serde has no usecase in android yet, hence removing the module.
  sdk/core/azure-core-customserde-json-jackson/CHANGELOG.md
  sdk/core/azure-core-customserde-json-jackson/README.md
  sdk/core/azure-core-customserde-json-jackson/build.gradle
  sdk/core/azure-core-customserde-json-jackson/src/main/AndroidManifest.xml
  sdk/core/azure-core-customserde-json-jackson/src/main/java/com/azure/core/customserde/json/jackson/JacksonJsonSerializer.java
  sdk/core/azure-core-customserde-json-jackson/src/main/java/com/azure/core/customserde/json/jackson/JacksonJsonSerializerBuilder.java
  sdk/core/azure-core-customserde-json-jackson/src/main/java/com/azure/core/customserde/json/jackson/JacksonJsonSerializerProvider.java
  sdk/core/azure-core-customserde-json-jackson/src/main/java/com/azure/core/customserde/json/jackson/package-info.java
  sdk/core/azure-core-customserde-json-jackson/src/main/resources/META-INF/services/com.azure.core.util.serializer.JsonSerializerProvider
  sdk/core/azure-core-customserde-json-jackson/src/main/resources/META-INF/services/com.azure.core.util.serializer.MemberNameConverterProvider
  sdk/core/azure-core-customserde-json-jackson/src/main/resources/azure-core.properties
  sdk/core/azure-core-customserde/CHANGELOG.md
  sdk/core/azure-core-customserde/README.md
  sdk/core/azure-core-customserde/build.gradle
  sdk/core/azure-core-customserde/src/main/AndroidManifest.xml
  sdk/core/azure-core-customserde/src/main/java/com/azure/core/customserde/JsonSerializer.java
  sdk/core/azure-core-customserde/src/main/java/com/azure/core/customserde/JsonSerializerProvider.java
  sdk/core/azure-core-customserde/src/main/java/com/azure/core/customserde/JsonSerializerProviders.java
  sdk/core/azure-core-customserde/src/main/java/com/azure/core/customserde/MemberNameConverter.java
  sdk/core/azure-core-customserde/src/main/java/com/azure/core/customserde/MemberNameConverterProvider.java
  sdk/core/azure-core-customserde/src/main/java/com/azure/core/customserde/MemberNameConverterProviders.java
  sdk/core/azure-core-customserde/src/main/java/com/azure/core/customserde/ObjectSerializer.java
  sdk/core/azure-core-customserde/src/main/java/com/azure/core/customserde/TypeReference.java
  sdk/core/azure-core-customserde/src/main/java/com/azure/core/customserde/package-info.java
  sdk/core/azure-core-customserde/src/main/resources/azure-core.properties
  sdk/core/azure-core-jackson/src/main/java/com/azure/android/core/serde/jackson/JacksonSerder.java
  settings.gradle
Labels: Azure.Core

#605 Fix incompatibility between String and CommunicationUserIdentifier when serialization [1.0.0-beta.6]
  README.md
  sdk/communication/azure-communication-chat/CHANGELOG.md
  sdk/communication/azure-communication-chat/README.md
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/ChatMessage.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/ChatMessageContent.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/ChatMessageReadReceipt.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/ChatParticipant.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/ChatThread.java
Labels: Communication

#606 Update version in both packages' CHANGELOG.md and build.gradle
  README.md
  sdk/communication/azure-communication-chat/CHANGELOG.md
  sdk/communication/azure-communication-chat/build.gradle
  sdk/communication/azure-communication-common/CHANGELOG.md
  sdk/communication/azure-communication-common/README.md
  sdk/communication/azure-communication-common/build.gradle
Labels: Communication

#607 Sync eng/common directory with azure-sdk-tools for PR 1447
  eng/common/scripts/Helpers/DevOps-WorkItem-Helpers.ps1
  eng/common/scripts/Prepare-Release.ps1
  eng/common/scripts/common.ps1
  eng/common/scripts/logging.ps1
Labels: Central-EngSys, EngSys
