Repository Azure/azure-sdk-for-android, pull requests merged in 2021-09, with the labels that each got.

#859 Sync eng/common directory with azure-sdk-tools for PR 1967
  eng/common/pipelines/templates/steps/daily-dev-build-variable.yml
Labels: EngSys, Central-EngSys

#860 Sync eng/common directory with azure-sdk-tools for PR 1972
  eng/common/scripts/Create-APIReview.ps1
  eng/common/scripts/SemVer.ps1
Labels: EngSys, Central-EngSys

#861 Changed UserAgentPolicy to correctly follow the guidelines about handling an `applicationId`.
  sdk/core/azure-core-http/src/main/java/com/azure/android/core/http/policy/UserAgentPolicy.java
  sdk/core/azure-core/CHANGELOG.md
Labels: Azure.Core

#863 Sync eng/common directory with azure-sdk-tools for PR 1986
  eng/common/testproxy/docker-start-proxy.ps1
Labels: EngSys, Central-EngSys

#866 Sync eng/common directory with azure-sdk-tools for PR 1982
  eng/common/pipelines/templates/steps/set-test-pipeline-version.yml
Labels: EngSys, Central-EngSys

#870 Sync eng/common directory with azure-sdk-tools for PR 1977
  eng/common/scripts/Update-DocsMsPackages.ps1
Labels: EngSys, Central-EngSys

#865 Azure Core beta release preparation for September 2021
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  sdk/core/azure-core-credential/CHANGELOG.md
  sdk/core/azure-core-credential/README.md
  sdk/core/azure-core-http-httpurlconnection/CHANGELOG.md
  sdk/core/azure-core-http-httpurlconnection/README.md
  sdk/core/azure-core-http-okhttp/CHANGELOG.md
  sdk/core/azure-core-http-okhttp/README.md
  sdk/core/azure-core-http/CHANGELOG.md
  sdk/core/azure-core-http/README.md
  sdk/core/azure-core-jackson/CHANGELOG.md
  sdk/core/azure-core-jackson/README.md
  sdk/core/azure-core-logging/CHANGELOG.md
  sdk/core/azure-core-logging/README.md
  sdk/core/azure-core-rest/CHANGELOG.md
  sdk/core/azure-core-rest/README.md
  sdk/core/azure-core-test/CHANGELOG.md
  sdk/core/azure-core-test/README.md
  sdk/core/azure-core/CHANGELOG.md
  sdk/core/azure-core/README.md
Labels: Azure.Core

#869 Sync eng/common directory with azure-sdk-tools for PR 1995
  eng/common/scripts/stress-testing/deploy-stress-tests.ps1
Labels: EngSys, Central-EngSys

#873 Updated Azure Core versions after September 2021 beta release.
  build.gradle
  sdk/core/azure-core-credential/CHANGELOG.md
  sdk/core/azure-core-credential/gradle.properties
  sdk/core/azure-core-http-httpurlconnection/CHANGELOG.md
  sdk/core/azure-core-http-httpurlconnection/gradle.properties
  sdk/core/azure-core-http-okhttp/CHANGELOG.md
  sdk/core/azure-core-http-okhttp/gradle.properties
  sdk/core/azure-core-http/CHANGELOG.md
  sdk/core/azure-core-http/gradle.properties
  sdk/core/azure-core-jackson/CHANGELOG.md
  sdk/core/azure-core-jackson/gradle.properties
  sdk/core/azure-core-logging/CHANGELOG.md
  sdk/core/azure-core-logging/gradle.properties
  sdk/core/azure-core-rest/CHANGELOG.md
  sdk/core/azure-core-rest/gradle.properties
  sdk/core/azure-core-test/CHANGELOG.md
  sdk/core/azure-core-test/gradle.properties
  sdk/core/azure-core/CHANGELOG.md
  sdk/core/azure-core/gradle.properties
Labels: Azure.Core

#871 Sync eng/common directory with azure-sdk-tools for PR 1983
  eng/common/TestResources/New-TestResources.ps1
  eng/common/TestResources/New-TestResources.ps1.md
  eng/common/TestResources/README.md
Labels: EngSys, Central-EngSys

#874 Sync eng/common directory with azure-sdk-tools for PR 1946
  eng/common/scripts/check-spelling-in-changed-files.ps1
Labels: EngSys, Central-EngSys

#875 Sync eng/common directory with azure-sdk-tools for PR 2006
  eng/common/scripts/SemVer.ps1
Labels: EngSys, Central-EngSys

#876 Sync eng/common directory with azure-sdk-tools for PR 1979
  eng/common/scripts/ChangeLog-Operations.ps1
  eng/common/scripts/Update-ChangeLog.ps1
Labels: EngSys, Central-EngSys

#879 Sync eng/common directory with azure-sdk-tools for PR 2008
  eng/common/scripts/ChangeLog-Operations.ps1
  eng/common/scripts/Prepare-Release.ps1
  eng/common/scripts/Update-ChangeLog.ps1
Labels: EngSys, Central-EngSys

#880 update trouter lib & update version
  build.gradle
  samples/sample-chat-app/src/main/java/com/azure/android/communication/chat/sampleapp/MainActivity.java
  sdk/communication/azure-communication-chat/CHANGELOG.md
  sdk/communication/azure-communication-chat/build.gradle
  sdk/communication/azure-communication-chat/env-prod.properties
  sdk/communication/azure-communication-chat/env-test.properties
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/ChatClientBuilder.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/ChatThreadClientBuilder.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/implementation/signaling/CommunicationListener.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/implementation/signaling/CommunicationSignalingClient.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/implementation/signaling/TrouterUtils.java
Labels: Communication

#881 Hotfix/azure communication chat 1.0.1
  README.md
  build.gradle
  samples/sample-chat-app/src/main/java/com/azure/android/communication/chat/sampleapp/MainActivity.java
  sdk/communication/azure-communication-chat/CHANGELOG.md
  sdk/communication/azure-communication-chat/README.md
  sdk/communication/azure-communication-chat/build.gradle
  sdk/communication/azure-communication-chat/env-prod.properties
  sdk/communication/azure-communication-chat/env-test.properties
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/ChatClientBuilder.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/ChatThreadClientBuilder.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/implementation/signaling/CommunicationListener.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/implementation/signaling/CommunicationSignalingClient.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/implementation/signaling/TrouterUtils.java
Labels: Communication

#877 Sync eng/common directory with azure-sdk-tools for PR 2009
  eng/common/pipelines/templates/steps/cache-ps-modules.yml
Labels: EngSys, Central-EngSys

#883 Sync eng/common directory with azure-sdk-tools for PR 2016
  eng/common/pipelines/templates/steps/verify-changelog.yml
Labels: EngSys, Central-EngSys

#884 fix internal trouter behavior for stop
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/implementation/signaling/CommunicationSignalingClient.java
Labels: Communication

#882 Sync eng/common directory with azure-sdk-tools for PR 2011
  eng/common/pipelines/templates/steps/detect-api-changes.yml
  eng/common/scripts/Detect-Api-Changes.ps1
Labels: EngSys, Central-EngSys

#885 Sync eng/common directory with azure-sdk-tools for PR 2010
  eng/common/scripts/ChangeLog-Operations.ps1
  eng/common/scripts/Prepare-Release.ps1
  eng/common/scripts/Update-ChangeLog.ps1
Labels: EngSys, Central-EngSys

#886 Sync eng/common directory with azure-sdk-tools for PR 2025
  eng/common/scripts/Collect-ChangeLogs.ps1
  eng/common/scripts/Update-ChangeLog.ps1
  eng/common/scripts/Verify-ChangeLog.ps1
Labels: EngSys, Central-EngSys

#888 Sync eng/common directory with azure-sdk-tools for PR 2035
  eng/common/scripts/Update-DocsMsPackages.ps1
Labels: EngSys, Central-EngSys

#890 Sync eng/common directory with azure-sdk-tools for PR 2031
  eng/common/pipelines/templates/steps/policheck.yml
Labels: EngSys, Central-EngSys

#878 ACS Chat SDK Sept release
  README.md
  build.gradle
  samples/sample-chat-app/src/main/java/com/azure/android/communication/chat/sampleapp/MainActivity.java
  sdk/communication/azure-communication-chat/CHANGELOG.md
  sdk/communication/azure-communication-chat/README.md
  sdk/communication/azure-communication-chat/env-prod.properties
  sdk/communication/azure-communication-chat/env-test.properties
  sdk/communication/azure-communication-chat/gradle.properties
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/ChatAsyncClient.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/ChatClient.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/ChatThreadAsyncClient.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/ChatThreadClient.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/implementation/notifications/NotificationUtils.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/implementation/notifications/fcm/PushNotificationClient.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/implementation/notifications/fcm/RegistrarClient.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/implementation/notifications/signaling/CommunicationListener.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/implementation/notifications/signaling/CommunicationSignalingClient.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/implementation/notifications/signaling/SignalingClient.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/ChatPushNotification.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/models/PushNotificationCallback.java
  sdk/communication/azure-communication-chat/src/test/java/com/azure/android/communication/chat/ChatThreadAsyncClientTest.java
Labels: Communication

#887 Sync eng/common directory with azure-sdk-tools for PR 2027
  eng/common/scripts/stress-testing/deploy-stress-tests.ps1
Labels: EngSys, Central-EngSys

#889 Sync eng/common directory with azure-sdk-tools for PR 2039
  eng/common/scripts/stress-testing/deploy-stress-tests.ps1
Labels: EngSys, Central-EngSys

#891 add hotfix version changelog to main branch
  sdk/communication/azure-communication-chat/CHANGELOG.md
Labels: Communication

#893 Sync eng/common directory with azure-sdk-tools for PR 2046
  eng/common/scripts/Detect-Api-Changes.ps1
Labels: EngSys, Central-EngSys
