Repository Azure/azure-sdk-for-android, pull requests merged in 2022-09, with the labels that each got.

#1187 Sync eng/common directory with azure-sdk-tools for PR 4041
  eng/common/pipelines/templates/steps/update-docsms-metadata.yml
Labels: EngSys, Central-EngSys

#1188 Sync eng/common directory with azure-sdk-tools for PR 4042
  eng/common/pipelines/templates/steps/docs-metadata-release.yml
  eng/common/pipelines/templates/steps/sparse-checkout.yml
  eng/common/pipelines/templates/steps/update-docsms-metadata.yml
Labels: EngSys, Central-EngSys

#1189 Add github actions based check enforcer
  .github/workflows/event.yml
Labels: Central-EngSys

#1191 Sync eng/common directory with azure-sdk-tools for PR 4128
  eng/common/pipelines/templates/steps/sparse-checkout.yml
Labels: EngSys, Central-EngSys

#1192 Sync eng/common directory with azure-sdk-tools for PR 4098
  eng/common/testproxy/test-proxy-docker.yml
  eng/common/testproxy/test-proxy-tool.yml
Labels: EngSys, Central-EngSys

#1193 Update check enforcer yaml permissions and name
  .github/workflows/event.yml
Labels: Central-EngSys

#1194 Sync eng/common directory with azure-sdk-tools for PR 4141
  eng/common/scripts/Helpers/DevOps-WorkItem-Helpers.ps1
  eng/common/scripts/Update-DevOps-Release-WorkItem.ps1
Labels: EngSys, Central-EngSys

#1196 Update azure-sdk-build-tools Repository Resource Refs in Yaml files
  sdk/communication/ci.yml
  sdk/core/ci.yml
Labels: Communication, Azure.Core

#1195 Sync eng/common directory with azure-sdk-tools for PR 4169
  eng/common/testproxy/target_version.txt
Labels: EngSys, Central-EngSys

#1197 Sync eng/common directory with azure-sdk-tools for PR 4212
  eng/common/testproxy/target_version.txt
Labels: EngSys, Central-EngSys

#1199 Sync eng/common directory with azure-sdk-tools for PR 4240
  eng/common/testproxy/target_version.txt
Labels: EngSys, Central-EngSys
