Repository Azure/azure-sdk-for-android, pull requests merged in 2022-11, with the labels that each got.

#1217 Sync eng/common directory with azure-sdk-tools for PR 4544
  eng/common/scripts/job-matrix/Create-JobMatrix.ps1
  eng/common/scripts/stress-testing/find-all-stress-packages.ps1
  eng/common/scripts/stress-testing/generate-scenario-matrix.ps1
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys

#1216 Sync eng/common directory with azure-sdk-tools for PR 4574
  eng/common/testproxy/target_version.txt
Labels: EngSys, Central-EngSys

#1219 Sync eng/common directory with azure-sdk-tools for PR 4591
  eng/common/scripts/stress-testing/find-all-stress-packages.ps1
Labels: EngSys, Central-EngSys

#1218 Sync eng/common directory with azure-sdk-tools for PR 4586
  eng/common/scripts/Update-DocsMsToc.ps1
Labels: EngSys, Central-EngSys

#1220 Sync eng/common directory with azure-sdk-tools for PR 4603
  eng/common/pipelines/templates/steps/check-spelling.yml
  eng/common/spelling/Invoke-Cspell.ps1
Labels: EngSys, Central-EngSys

#1221 Sync eng/common directory with azure-sdk-tools for PR 4606
  eng/common/testproxy/target_version.txt
Labels: EngSys, Central-EngSys

#1222 Sync eng/common directory with azure-sdk-tools for PR 4622
  eng/common/TestResources/clouds/AzureCloud.json
Labels: EngSys, Central-EngSys

#1223 Sync eng/common directory with azure-sdk-tools for PR 4629
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys

#1224 Prepare Core beta release for October 2022
  build.gradle
  sdk/communication/azure-communication-common/CHANGELOG.md
  sdk/communication/azure-communication-common/build.gradle
  sdk/core/azure-core-credential/CHANGELOG.md
  sdk/core/azure-core-credential/README.md
  sdk/core/azure-core-http-httpurlconnection/CHANGELOG.md
  sdk/core/azure-core-http-httpurlconnection/README.md
  sdk/core/azure-core-http-okhttp/CHANGELOG.md
  sdk/core/azure-core-http-okhttp/README.md
  sdk/core/azure-core-http/CHANGELOG.md
  sdk/core/azure-core-http/README.md
  sdk/core/azure-core-jackson/CHANGELOG.md
  sdk/core/azure-core-jackson/README.md
  sdk/core/azure-core-jackson/build.gradle
  sdk/core/azure-core-logging/CHANGELOG.md
  sdk/core/azure-core-logging/README.md
  sdk/core/azure-core-rest/CHANGELOG.md
  sdk/core/azure-core-rest/README.md
  sdk/core/azure-core-test/CHANGELOG.md
  sdk/core/azure-core-test/README.md
  sdk/core/azure-core-test/build.gradle
  sdk/core/azure-core/CHANGELOG.md
  sdk/core/azure-core/README.md
Labels: Client, Azure.Core

#1225 Revert "Update azure-sdk-build-tools Repository Resource Refs in Yaml files"
  sdk/communication/ci.yml
  sdk/core/ci.yml
Labels: Communication, Azure.Core

#1226 Updating check enforcer permissions to enable writing comments
  .github/workflows/event.yml
Labels: Central-EngSys

#1227 Increment versions after Core release for November 2022
  README.md
  build.gradle
  sdk/communication/azure-communication-chat/CHANGELOG.md
  sdk/communication/azure-communication-common/CHANGELOG.md
  sdk/core/azure-core-credential/CHANGELOG.md
  sdk/core/azure-core-credential/gradle.properties
  sdk/core/azure-core-http-httpurlconnection/CHANGELOG.md
  sdk/core/azure-core-http-httpurlconnection/gradle.properties
  sdk/core/azure-core-http-okhttp/CHANGELOG.md
  sdk/core/azure-core-http-okhttp/gradle.properties
  sdk/core/azure-core-http/CHANGELOG.md
  sdk/core/azure-core-http/gradle.properties
  sdk/core/azure-core-jackson/CHANGELOG.md
  sdk/core/azure-core-jackson/gradle.properties
  sdk/core/azure-core-logging/CHANGELOG.md
  sdk/core/azure-core-logging/gradle.properties
  sdk/core/azure-core-rest/CHANGELOG.md
  sdk/core/azure-core-rest/gradle.properties
  sdk/core/azure-core-test/CHANGELOG.md
  sdk/core/azure-core-test/gradle.properties
  sdk/core/azure-core/CHANGELOG.md
  sdk/core/azure-core/gradle.properties
Labels: Client, Communication, Azure.Core

#1228 Sync eng/common directory with azure-sdk-tools for PR 4623
  eng/common/TestResources/New-TestResources.ps1
Labels: EngSys, Central-EngSys

#1229 Sync eng/common directory with azure-sdk-tools for PR 4666
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys

#1230 Sync eng/common directory with azure-sdk-tools for PR 4631
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys

#1232 Prepare ACS Common a minor release - 1.1.0
  sdk/communication/azure-communication-common/CHANGELOG.md
  sdk/communication/azure-communication-common/README.md
  sdk/communication/azure-communication-common/gradle.properties
Labels: Communication, Communication - Common

#1233 Post release updates for ACS Common
  build.gradle
  sdk/communication/azure-communication-common/CHANGELOG.md
  sdk/communication/azure-communication-common/gradle.properties
Labels: Communication

#1237 Sync eng/common directory with azure-sdk-tools for PR 4687
  eng/common/testproxy/target_version.txt
Labels: EngSys, Central-EngSys

#1239 Sync eng/common directory with azure-sdk-tools for PR 4632
  eng/common/scripts/Helpers/Metadata-Helpers.ps1
  eng/common/scripts/Helpers/Service-Level-Readme-Automation-Helpers.ps1
  eng/common/scripts/Service-Level-Readme-Automation.ps1
Labels: EngSys, Central-EngSys

#1241 Sync eng/common directory with azure-sdk-tools for PR 4701
  eng/common/scripts/Queue-Pipeline.ps1
Labels: EngSys, Central-EngSys

#1242 Sync eng/common directory with azure-sdk-tools for PR 4726
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys

#1235 Sync eng/common directory with azure-sdk-tools for PR 4628
  eng/common/scripts/Create-APIReview.ps1
  eng/common/scripts/Helpers/ApiView-Helpers.ps1
  eng/common/scripts/Prepare-Release.ps1
Labels: EngSys, Central-EngSys

#1243 Sync eng/common directory with azure-sdk-tools for PR 4728
  eng/common/scripts/Helpers/Metadata-Helpers.ps1
Labels: EngSys, Central-EngSys

#1244 Sync eng/common directory with azure-sdk-tools for PR 4746
  eng/common/scripts/git-branch-push.ps1
Labels: EngSys, Central-EngSys

#1245 Sync eng/common directory with azure-sdk-tools for PR 4713
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys
