Repository Azure/azure-sdk-for-android, pull requests merged in 2022-10, with the labels that each got.

#1201 Sync eng/common directory with azure-sdk-tools for PR 4315
  eng/common/testproxy/target_version.txt
Labels: EngSys, Central-EngSys

#1202 Sync eng/common directory with azure-sdk-tools for PR 4311
  eng/common/scripts/Verify-Links.ps1
Labels: EngSys, Central-EngSys

#1204 Add default .assets directory to .gitignore
  .gitignore
Labels: Central-EngSys

#1203 Sync eng/common directory with azure-sdk-tools for PR 4341
  eng/common/testproxy/target_version.txt
Labels: EngSys, Central-EngSys

#1208 Sync eng/common directory with azure-sdk-tools for PR 3790
  eng/common/scripts/Helpers/PSModule-Helpers.ps1
  eng/common/scripts/job-matrix/Create-JobMatrix.ps1
  eng/common/scripts/job-matrix/job-matrix-functions.ps1
  eng/common/scripts/stress-testing/deploy-stress-tests.ps1
  eng/common/scripts/stress-testing/find-all-stress-packages.ps1
  eng/common/scripts/stress-testing/generate-scenario-matrix.ps1
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys

#1209 Sync eng/common directory with azure-sdk-tools for PR 4486
  eng/common/spelling/Invoke-Cspell.ps1
  eng/common/spelling/package-lock.json
  eng/common/spelling/package.json
Labels: EngSys, Central-EngSys

#1210 Sync eng/common directory with azure-sdk-tools for PR 4480
  eng/common/scripts/Update-DocsMsToc.ps1
Labels: EngSys, Central-EngSys

#1211 Sync eng/common directory with azure-sdk-tools for PR 4504
  eng/common/scripts/stress-testing/generate-scenario-matrix.ps1
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys

#1207 Fix phone number serialization
  sdk/communication/azure-communication-common/CHANGELOG.md
  sdk/communication/azure-communication-common/src/main/java/com/azure/android/communication/common/CommunicationIdentifier.java
  sdk/communication/azure-communication-common/src/main/java/com/azure/android/communication/common/PhoneNumberIdentifier.java
  sdk/communication/azure-communication-common/src/test/java/com/azure/android/communication/common/CommunicationIdentifierTests.java
Labels: Communication, Communication - Common

#1212 Sync eng/common directory with azure-sdk-tools for PR 4527
  eng/common/testproxy/target_version.txt
Labels: EngSys, Central-EngSys

#1214 Sync eng/common directory with azure-sdk-tools for PR 4543
  eng/common/scripts/stress-testing/find-all-stress-packages.ps1
Labels: EngSys, Central-EngSys

#1213 Sync eng/common directory with azure-sdk-tools for PR 4532
  eng/common/TestResources/New-TestResources.ps1
Labels: EngSys, Central-EngSys
