Repository Azure/azure-sdk-for-android, pull requests merged in 2022-03, with the labels that each got.

#1028 Support parsing ACS gcch & ACS dod mri in notifications
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/implementation/notifications/NotificationUtils.java
  sdk/communication/azure-communication-chat/src/test/java/com/azure/android/communication/chat/implementation/notification/NotificationUtilsTest.java
Labels: Communication

#1031 Sync eng/common directory with azure-sdk-tools for PR 2778
  eng/common/pipelines/templates/steps/credscan.yml
  eng/common/scripts/update-docs-metadata.ps1
Labels: EngSys, Central-EngSys

#1032 Sync eng/common directory with azure-sdk-tools for PR 2833
  eng/common/pipelines/templates/steps/detect-api-changes.yml
  eng/common/scripts/Detect-Api-Changes.ps1
Labels: EngSys, Central-EngSys

#1033 Sync eng/common directory with azure-sdk-tools for PR 2823
  eng/common/testproxy/docker-start-proxy.ps1
  eng/common/testproxy/target_version.txt
  eng/common/testproxy/test-proxy-docker.yml
  eng/common/testproxy/test-proxy-tool.yml
Labels: EngSys, Central-EngSys

#1030 Sync eng/common directory with azure-sdk-tools for PR 2830
  eng/common/pipelines/templates/steps/cosmos-emulator.yml
  eng/common/scripts/Cosmos-Emulator.ps1
Labels: EngSys, Central-EngSys

#1035 Sync eng/common directory with azure-sdk-tools for PR 2824
  eng/common/scripts/git-diff-changes.ps1
Labels: EngSys, Central-EngSys

#1037 Sync eng/common directory with azure-sdk-tools for PR 2875
  eng/common/pipelines/templates/steps/detect-api-changes.yml
  eng/common/scripts/Detect-Api-Changes.ps1
Labels: EngSys, Central-EngSys

#1038 Prepare Azure Core patch release for March 2022
  build.gradle
  sdk/core/azure-core-credential/CHANGELOG.md
  sdk/core/azure-core-credential/README.md
  sdk/core/azure-core-http-httpurlconnection/CHANGELOG.md
  sdk/core/azure-core-http-httpurlconnection/README.md
  sdk/core/azure-core-http-okhttp/CHANGELOG.md
  sdk/core/azure-core-http-okhttp/README.md
  sdk/core/azure-core-http/CHANGELOG.md
  sdk/core/azure-core-http/README.md
  sdk/core/azure-core-jackson/CHANGELOG.md
  sdk/core/azure-core-jackson/README.md
  sdk/core/azure-core-jackson/build.gradle
  sdk/core/azure-core-logging/CHANGELOG.md
  sdk/core/azure-core-logging/README.md
  sdk/core/azure-core-rest/CHANGELOG.md
  sdk/core/azure-core-rest/README.md
  sdk/core/azure-core-test/CHANGELOG.md
  sdk/core/azure-core-test/README.md
  sdk/core/azure-core-test/build.gradle
  sdk/core/azure-core/CHANGELOG.md
  sdk/core/azure-core/README.md
Labels: Client, Azure.Core

#1026 Sync eng/common directory with azure-sdk-tools for PR 2810
  eng/common/TestResources/New-TestResources.ps1
  eng/common/TestResources/SubConfig-Helpers.ps1
Labels: EngSys, Central-EngSys

#1039 Sync eng/common directory with azure-sdk-tools for PR 2889
  eng/common/TestResources/New-TestResources.ps1
Labels: EngSys, Central-EngSys

#1040 Sync eng/common directory with azure-sdk-tools for PR 2892
  eng/common/scripts/stress-testing/deploy-stress-tests.ps1
  eng/common/scripts/stress-testing/find-all-stress-packages.ps1
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys

#1034 Sync eng/common directory with azure-sdk-tools for PR 2836
  eng/common/scripts/ChangeLog-Operations.ps1
Labels: EngSys, Central-EngSys

#1041 Sync eng/common directory with azure-sdk-tools for PR 2899
  eng/common/scripts/ChangeLog-Operations.ps1
Labels: EngSys, Central-EngSys

#1042 Pin version of build tools repo
  sdk/communication/ci.yml
  sdk/core/ci.yml
Labels: Azure.Core

#1044 Prepare ACS Common patch release for March 2022.
  sdk/communication/azure-communication-common/CHANGELOG.md
  sdk/communication/azure-communication-common/README.md
  sdk/communication/azure-communication-common/gradle.properties
Labels: Client, Communication

#1046 Increment ACS Common version after patch release.
  build.gradle
  sdk/communication/azure-communication-common/CHANGELOG.md
  sdk/communication/azure-communication-common/gradle.properties
Labels: Client, Communication

#1048 Sync eng/common directory with azure-sdk-tools for PR 2910
  eng/common/scripts/Update-DocsMsMetadata.ps1
Labels: EngSys, Central-EngSys

#1050 Increment ACS Chat versions after patch release.
  sdk/communication/azure-communication-chat/CHANGELOG.md
  sdk/communication/azure-communication-chat/README.md
Labels: Communication

#1052 Sync eng/common directory with azure-sdk-tools for PR 2870
  eng/common/pipelines/templates/jobs/archetype-sdk-tests-generate.yml
Labels: EngSys, Central-EngSys

#1053 Sync eng/common directory with azure-sdk-tools for PR 2866
  eng/common/TestResources/New-TestResources.ps1
Labels: EngSys, Central-EngSys

#1055 Sync eng/common directory with azure-sdk-tools for PR 2901
  eng/common/pipelines/templates/steps/credscan.yml
Labels: EngSys, Central-EngSys

#1056 Sync eng/common directory with azure-sdk-tools for PR 2922
  eng/common/scripts/Update-DocsMsToc.ps1
Labels: EngSys, Central-EngSys

#1059 Sync eng/common directory with azure-sdk-tools for PR 2847
  eng/common/scripts/Helpers/Metadata-Helpers.ps1
  eng/common/scripts/Import-AzModules.ps1
  eng/common/scripts/Update-DocsMsMetadata.ps1
Labels: EngSys, Central-EngSys

#1061 Sync eng/common directory with azure-sdk-tools for PR 2939
  eng/common/scripts/Update-DocsMsToc.ps1
Labels: EngSys, Central-EngSys

#1062 Sync eng/common directory with azure-sdk-tools for PR 2938
  eng/common/scripts/Update-DocsMsToc.ps1
Labels: EngSys, Central-EngSys

#1063 Sync eng/common directory with azure-sdk-tools for PR 2972
  eng/common/pipelines/templates/steps/eng-common-workflow-enforcer.yml
  eng/common/scripts/Helpers/git-helpers.ps1
Labels: EngSys, Central-EngSys
