Repository Azure/azure-sdk-for-android, pull requests merged in 2023-04, with the labels that each got.

#1342 Sync eng/common directory with azure-sdk-tools for PR 5918
  eng/common/pipelines/templates/steps/credscan.yml
Labels: EngSys, Central-EngSys

#1343 Sync eng/common directory with azure-sdk-tools for PR 5924
  eng/common/TestResources/SubConfig-Helpers.ps1
Labels: EngSys, Central-EngSys

#1341 [android] azure-communication-common release
  sdk/communication/azure-communication-common/CHANGELOG.md
  sdk/communication/azure-communication-common/README.md
Labels: Communication, Communication - Identity

#1344 [android] Post release updates for ACS Common
  build.gradle
  sdk/communication/azure-communication-common/CHANGELOG.md
  sdk/communication/azure-communication-common/gradle.properties
Labels: Communication, Communication - Identity

#1348 Sync eng/common directory with azure-sdk-tools for PR 5951
  eng/common/scripts/Add-RetentionLease.ps1
  eng/common/scripts/Invoke-DevOpsAPI.ps1
  eng/common/scripts/Queue-Pipeline.ps1
  eng/common/scripts/logging.ps1
Labels: EngSys, Central-EngSys

#1352 Sync eng/common directory with azure-sdk-tools for PR 5995
  eng/common/scripts/TypeSpec-Project-Sync.ps1
Labels: EngSys, Central-EngSys

#1355 Sync eng/common directory with azure-sdk-tools for PR 6004
  eng/common/pipelines/templates/jobs/archetype-sdk-tests-generate.yml
  eng/common/pipelines/templates/jobs/prepare-pipelines.yml
  eng/common/pipelines/templates/stages/archetype-sdk-tool-pwsh.yml
Labels: EngSys, Central-EngSys

#1356 Sync eng/common directory with azure-sdk-tools for PR 5911
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys

#1361 Sync eng/common directory with azure-sdk-tools for PR 6045
  eng/common/scripts/Verify-RequiredDocsJsonMembers.ps1
Labels: EngSys, Central-EngSys

#1360 Enable event processor for Android
  .github/event-processor.config
  .github/fabricbot.json
  .github/workflows/event-processor.yml
  .github/workflows/scheduled-event-processor.yml
  eng/scripts/Language-Settings.ps1
Labels: Central-EngSys
