Repository Azure/azure-sdk-for-android, pull requests merged in 2023-10, with the labels that each got.

#1436 Sync eng/common directory with azure-sdk-tools for PR 7040
  eng/common/pipelines/templates/steps/update-docsms-metadata.yml
  eng/common/scripts/Helpers/Metadata-Helpers.ps1
  eng/common/scripts/Helpers/Service-Level-Readme-Automation-Helpers.ps1
  eng/common/scripts/Service-Level-Readme-Automation.ps1
  eng/common/scripts/Update-DocsMsMetadata.ps1
  eng/common/scripts/get-codeowners.lib.ps1
  eng/common/scripts/get-codeowners.ps1
Labels: EngSys, Central-EngSys

#1437 Sync .github/workflows directory with azure-sdk-tools for PR 7071
  .github/workflows/event-processor.yml
  .github/workflows/scheduled-event-processor.yml
Labels: EngSys, Central-EngSys

#1439 Sync eng/common directory with azure-sdk-tools for PR 7072
  eng/common/pipelines/templates/steps/eng-common-workflow-enforcer.yml
Labels: EngSys, Central-EngSys

#1442 Sync .github/workflows directory with azure-sdk-tools for PR 7098
  .github/workflows/event-processor.yml
  .github/workflows/scheduled-event-processor.yml
Labels: EngSys, Central-EngSys

#1440 Sync eng/common directory with azure-sdk-tools for PR 7067
  eng/common/scripts/TypeSpec-Project-Generate.ps1
Labels: EngSys, Central-EngSys

#1443 Sync eng/common directory with azure-sdk-tools for PR 7106
  eng/common/pipelines/templates/steps/sparse-checkout.yml
Labels: EngSys, Central-EngSys

#1434 Jimin/eudb
  sdk/communication/azure-communication-chat/env-prod.properties
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/implementation/notifications/NotificationUtils.java
  sdk/communication/azure-communication-chat/src/main/java/com/azure/android/communication/chat/implementation/notifications/signaling/CommunicationSignalingClient.java
  sdk/communication/azure-communication-chat/src/test/java/com/azure/android/communication/chat/implementation/notification/NotificationUtilsTest.java
Labels: Communication

#1446 Update dependencies and prepare Azure Core release for Oct 2023
  build.gradle
  sdk/core/azure-core-credential/CHANGELOG.md
  sdk/core/azure-core-credential/README.md
  sdk/core/azure-core-http-httpurlconnection/CHANGELOG.md
  sdk/core/azure-core-http-httpurlconnection/README.md
  sdk/core/azure-core-http-okhttp/CHANGELOG.md
  sdk/core/azure-core-http-okhttp/README.md
  sdk/core/azure-core-http-okhttp/build.gradle
  sdk/core/azure-core-http/CHANGELOG.md
  sdk/core/azure-core-http/README.md
  sdk/core/azure-core-jackson/CHANGELOG.md
  sdk/core/azure-core-jackson/README.md
  sdk/core/azure-core-logging/CHANGELOG.md
  sdk/core/azure-core-logging/README.md
  sdk/core/azure-core-rest/CHANGELOG.md
  sdk/core/azure-core-rest/README.md
  sdk/core/azure-core-test/CHANGELOG.md
  sdk/core/azure-core-test/README.md
  sdk/core/azure-core/CHANGELOG.md
  sdk/core/azure-core/README.md
Labels: Client, Azure.Core

#1441 Sync eng/common directory with azure-sdk-tools for PR 7075
  eng/common/scripts/Helpers/DevOps-WorkItem-Helpers.ps1
Labels: EngSys, Central-EngSys

#1444 Sync eng/common directory with azure-sdk-tools for PR 7113
  eng/common/TestResources/New-TestResources.ps1
Labels: EngSys, Central-EngSys

#1447 Sync eng/common directory with azure-sdk-tools for PR 7171
  eng/common/TestResources/Update-TestResources.ps1
Labels: EngSys, Central-EngSys

#1451 Sync eng/common directory with azure-sdk-tools for PR 7185
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys

#1450 Updated build.gradle and CHANGELOG after ACS Common patch release.
  build.gradle
  sdk/communication/azure-communication-common/CHANGELOG.md
Labels: Client, Communication - Common

#1452 Sync eng/common directory with azure-sdk-tools for PR 7181
  eng/common/scripts/Delete-RemoteBranches.ps1
Labels: EngSys, Central-EngSys

#1455 Sync eng/common directory with azure-sdk-tools for PR 7191
  eng/common/scripts/copy-from-blobstorage.ps1
Labels: EngSys, Central-EngSys

#1454 update after release
  sdk/communication/azure-communication-chat/CHANGELOG.md
  sdk/communication/azure-communication-chat/gradle.properties
Labels: Communication

#1456 Sync eng/common directory with azure-sdk-tools for PR 7200
  eng/common/scripts/Save-Package-Properties.ps1
Labels: EngSys, Central-EngSys

#1458 Sync eng/common directory with azure-sdk-tools for PR 5947
  eng/common/pipelines/templates/jobs/prepare-pipelines.yml
Labels: EngSys, Central-EngSys
