Repository Azure/azure-sdk-for-android, pull requests merged in 2023-05, with the labels that each got.

#1366 Sync eng/common directory with azure-sdk-tools for PR 6063
  eng/common/testproxy/target_version.txt
Labels: EngSys, Central-EngSys

#1368 Sync eng/common directory with azure-sdk-tools for PR 6086
  eng/common/pipelines/templates/steps/detect-api-changes.yml
Labels: EngSys, Central-EngSys

#1369 Sync eng/common directory with azure-sdk-tools for PR 6061
  eng/common/pipelines/templates/steps/eng-common-workflow-enforcer.yml
  eng/common/scripts/Delete-RemoteBranches.ps1
Labels: EngSys, Central-EngSys

#1370 Sync .github/workflows directory with azure-sdk-tools for PR 6101
  .github/workflows/event-processor.yml
  .github/workflows/scheduled-event-processor.yml
Labels: EngSys, Central-EngSys

#1371 Sync eng/common directory with azure-sdk-tools for PR 6118
  eng/common/testproxy/transition-scripts/README.md
Labels: EngSys, Central-EngSys

#1372 Sync eng/common directory with azure-sdk-tools for PR 6103
  eng/common/scripts/stress-testing/deploy-stress-tests.ps1
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys

#1374 Prepare ACS Common for a beta release - 2.0.0-beta.2
  sdk/communication/azure-communication-common/CHANGELOG.md
  sdk/communication/azure-communication-common/README.md
Labels: Communication - Identity

#1375 Post release updates for acs common
  build.gradle
  sdk/communication/azure-communication-common/CHANGELOG.md
  sdk/communication/azure-communication-common/gradle.properties
Labels: Communication - Common

#1378 Sync eng/common directory with azure-sdk-tools for PR 6208
  eng/common/scripts/Test-SampleMetadata.ps1
Labels: EngSys, Central-EngSys

#1379 Sync eng/common directory with azure-sdk-tools for PR 6197
  eng/common/scripts/TypeSpec-Project-Generate.ps1
Labels: EngSys, Central-EngSys

#1381 Sync eng/common directory with azure-sdk-tools for PR 6230
  eng/common/testproxy/publish-proxy-logs.yml
Labels: EngSys, Central-EngSys

#1382 Sync eng/common directory with azure-sdk-tools for PR 6235
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys

#1380 Sync eng/common directory with azure-sdk-tools for PR 6202
  eng/common/scripts/TypeSpec-Project-Process.ps1
Labels: EngSys, Central-EngSys

#1383 Sync eng/common directory with azure-sdk-tools for PR 6248
  eng/common/pipelines/templates/steps/docs-metadata-release.yml
Labels: EngSys, Central-EngSys

#1384 Sync eng/common directory with azure-sdk-tools for PR 6244
  eng/common/scripts/TypeSpec-Project-Generate.ps1
Labels: EngSys, Central-EngSys

#1387 Sync eng/common directory with azure-sdk-tools for PR 6222
  eng/common/scripts/TypeSpec-Project-Process.ps1
Labels: EngSys, Central-EngSys

#1388 Sync eng/common directory with azure-sdk-tools for PR 6250
  eng/common/scripts/TypeSpec-Project-Process.ps1
Labels: EngSys, Central-EngSys
