Repository Azure/azure-sdk-for-android, pull requests merged in 2023-01, with the labels that each got.

#1273 Sync eng/common directory with azure-sdk-tools for PR 5005
  eng/common/pipelines/templates/jobs/archetype-sdk-tests-generate.yml
  eng/common/pipelines/templates/jobs/perf.yml
  eng/common/pipelines/templates/jobs/prepare-pipelines.yml
Labels: EngSys, Central-EngSys

#1274 Sync eng/common directory with azure-sdk-tools for PR 5027
  eng/common/scripts/job-matrix/README.md
  eng/common/scripts/job-matrix/samples/matrix-job-sample.yml
  eng/common/scripts/job-matrix/samples/matrix-test.yml
  eng/common/scripts/job-matrix/samples/matrix.json
  eng/common/scripts/job-matrix/tests/job-matrix-functions.filter.tests.ps1
  eng/common/scripts/job-matrix/tests/job-matrix-functions.modification.tests.ps1
  eng/common/scripts/job-matrix/tests/job-matrix-functions.tests.ps1
  eng/common/scripts/job-matrix/tests/test-import-matrix.json
Labels: EngSys, Central-EngSys

#1275 Sync eng/common directory with azure-sdk-tools for PR 5054
  eng/common/pipelines/templates/jobs/perf.yml
Labels: EngSys, Central-EngSys

#1276 Sync eng/common directory with azure-sdk-tools for PR 5059
  eng/common/scripts/job-matrix/README.md
Labels: EngSys, Central-EngSys

#1277 Sync eng/common directory with azure-sdk-tools for PR 5040
  eng/common/pipelines/templates/stages/archetype-sdk-tool-pwsh.yml
  eng/common/pipelines/templates/steps/run-pester-tests.yml
Labels: EngSys, Central-EngSys

#1278 Sync eng/common directory with azure-sdk-tools for PR 5085
  eng/common/scripts/get-codeowners.ps1
Labels: EngSys, Central-EngSys

#1279 Sync eng/common directory with azure-sdk-tools for PR 5095
  eng/common/scripts/job-matrix/job-matrix-functions.ps1
Labels: EngSys, Central-EngSys

#1280 Sync eng/common directory with azure-sdk-tools for PR 5121
  eng/common/scripts/Helpers/Service-Level-Readme-Automation-Helpers.ps1
Labels: EngSys, Central-EngSys

#1282 Sync eng/common directory with azure-sdk-tools for PR 5113
  eng/common/scripts/Update-DocsMsMetadata.ps1
Labels: EngSys, Central-EngSys

#1283 Sync eng/common directory with azure-sdk-tools for PR 5134
  eng/common/scripts/get-codeowners.ps1
Labels: EngSys, Central-EngSys

#1238 Remove duplicate permission from manifest
  sdk/communication/azure-communication-chat/src/main/AndroidManifest.xml
Labels: Communication, Community Contribution, customer-reported

#1286 Remove CHECKENFORCER file
  eng/CHECKENFORCER
Labels: Central-EngSys

#1284 Sync eng/common directory with azure-sdk-tools for PR 5169
  eng/common/TestResources/New-TestResources.ps1
Labels: EngSys, Central-EngSys

#1287 Sync eng/common directory with azure-sdk-tools for PR 5224
  eng/common/testproxy/publish-proxy-logs.yml
  eng/common/testproxy/test-proxy-tool.yml
Labels: EngSys, Central-EngSys

#1289 Sync eng/common directory with azure-sdk-tools for PR 5242
  eng/common/TestResources/New-TestResources.ps1
  eng/common/TestResources/Remove-TestResources.ps1
  eng/common/TestResources/SubConfig-Helpers.ps1
  eng/common/TestResources/Update-TestResources.ps1
Labels: EngSys, Central-EngSys

#1288 Sync eng/common directory with azure-sdk-tools for PR 5231
  eng/common/scripts/Cadl-Project-Generate.ps1
  eng/common/scripts/Cadl-Project-Sync.ps1
  eng/common/scripts/common.ps1
Labels: EngSys, Central-EngSys

#1292 Sync eng/common directory with azure-sdk-tools for PR 5272
  eng/common/scripts/Cadl-Project-Generate.ps1
  eng/common/scripts/Cadl-Project-Sync.ps1
Labels: EngSys, Central-EngSys
