Repository Azure/azure-sdk-for-android, pull requests merged in 2024-01, with the labels that each got.

#1482 Sync eng/common directory with azure-sdk-tools for PR 7468
  eng/common/scripts/Submit-PullRequest.ps1
Labels: EngSys, Central-EngSys

#1484 Sync eng/common directory with azure-sdk-tools for PR 7459
  eng/common/testproxy/scripts/tag-merge/README.md
  eng/common/testproxy/scripts/tag-merge/merge-proxy-tags.ps1
Labels: EngSys, Central-EngSys

#1485 Sync eng/common directory with azure-sdk-tools for PR 7498
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys

#1486 Sync eng/common directory with azure-sdk-tools for PR 7445
  eng/common/pipelines/templates/steps/create-tags-and-git-release.yml
  eng/common/scripts/create-tags-and-git-release.ps1
Labels: EngSys, Central-EngSys

#1489 Sync eng/common directory with azure-sdk-tools for PR 7451
  eng/common/pipelines/templates/steps/verify-restapi-spec-location.yml
  eng/common/scripts/Invoke-GitHubAPI.ps1
  eng/common/scripts/Verify-RestApiSpecLocation.ps1
Labels: EngSys, Central-EngSys

#1490 Sync eng/common directory with azure-sdk-tools for PR 7528
  eng/common/scripts/Verify-RestApiSpecLocation.ps1
Labels: EngSys, Central-EngSys

#1493 [CODEOWNERS] Remove automation section
  .github/CODEOWNERS
Labels: EngSys, Client

#1488 Sync eng/common directory with azure-sdk-tools for PR 7512
  eng/common/scripts/Generate-PR-Diff.ps1
Labels: EngSys, Central-EngSys

#1495 Sync eng/common directory with azure-sdk-tools for PR 7537
  eng/common/scripts/Helpers/git-helpers.ps1
  eng/common/scripts/Helpers/git-helpers.tests.ps1
  eng/common/testproxy/onboarding/common-asset-functions.ps1
  eng/common/testproxy/scripts/resolve-asset-conflict/README.md
  eng/common/testproxy/scripts/resolve-asset-conflict/resolve-asset-conflict.ps1
  eng/common/testproxy/scripts/tag-merge/README.md
  eng/common/testproxy/scripts/tag-merge/merge-proxy-tags.ps1
Labels: EngSys, Central-EngSys

#1496 Sync eng/common directory with azure-sdk-tools for PR 7543
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys

#1491 Fix duplicate real time notifications
  sdk/communication/azure-communication-chat/CHANGELOG.md
  sdk/communication/azure-communication-chat/README.md
  sdk/communication/azure-communication-chat/env-prod.properties
  sdk/communication/azure-communication-chat/env-test.properties
  sdk/communication/azure-communication-chat/gradle.properties
Labels: Communication

#1497 Sync eng/common directory with azure-sdk-tools for PR 7548
  eng/common/scripts/Verify-RestApiSpecLocation.ps1
Labels: EngSys, Central-EngSys

#1498 Sync eng/common directory with azure-sdk-tools for PR 7270
  eng/common/scripts/ChangeLog-Operations.ps1
  eng/common/scripts/Invoke-DevOpsAPI.ps1
  eng/common/scripts/Package-Properties.ps1
  eng/common/scripts/Update-ChangeLog.ps1
  eng/common/scripts/artifact-metadata-parsing.ps1
  eng/common/scripts/git-branch-push.ps1
Labels: EngSys, Central-EngSys

#1499 Sync eng/common directory with azure-sdk-tools for PR 7556
  eng/common/testproxy/scripts/tag-merge/merge-proxy-tags.ps1
Labels: EngSys, Central-EngSys

#1501 Sync eng/common directory with azure-sdk-tools for PR 7580
  eng/common/TestResources/New-TestResources.ps1
  eng/common/TestResources/New-TestResources.ps1.md
Labels: EngSys, Central-EngSys

#1500 Sync eng/common directory with azure-sdk-tools for PR 7569
  eng/common/scripts/Verify-RestApiSpecLocation.ps1
Labels: EngSys, Central-EngSys

#1502 Sync eng/common directory with azure-sdk-tools for PR 7584
  eng/common/TestResources/New-TestResources.ps1
Labels: EngSys, Central-EngSys

#1503 Jimin/trouter
  sdk/communication/azure-communication-chat/CHANGELOG.md
  sdk/communication/azure-communication-chat/README.md
  sdk/communication/azure-communication-chat/gradle.properties
Labels: Communication

#1504 Sync eng/common directory with azure-sdk-tools for PR 7585
  eng/common/scripts/Verify-RestApiSpecLocation.ps1
Labels: EngSys, Central-EngSys
