Repository Azure/azure-sdk-for-android, pull requests merged in 2024-02, with the labels that each got.

#1505 Sync eng/common directory with azure-sdk-tools for PR 7615
  eng/common/scripts/Prepare-Release.ps1
Labels: EngSys, Central-EngSys

#1507 Sync eng/common directory with azure-sdk-tools for PR 7629
  eng/common/docgeneration/Generate-DocIndex.ps1
  eng/common/pipelines/templates/jobs/docindex.yml
Labels: EngSys, Central-EngSys

#1509 Sync eng/common directory with azure-sdk-tools for PR 7634
  eng/common/pipelines/templates/steps/sparse-checkout.yml
Labels: EngSys, Central-EngSys

#1510 Sync eng/common directory with azure-sdk-tools for PR 7630
  eng/common/scripts/Invoke-GitHubAPI.ps1
Labels: EngSys, Central-EngSys

#1511 Sync .github/workflows directory with azure-sdk-tools for PR 7656
  .github/workflows/event-processor.yml
Labels: EngSys, Central-EngSys

#1512 Sync eng/common directory with azure-sdk-tools for PR 7664
  eng/common/TestResources/New-TestResources.ps1
Labels: EngSys, Central-EngSys

#1513 Sync eng/common directory with azure-sdk-tools for PR 7665
  eng/common/spelling/Invoke-Cspell.ps1
Labels: EngSys, Central-EngSys

#1516 Sync eng/common directory with azure-sdk-tools for PR 7655
  eng/common/scripts/typespec/New-EmitterPackageJson.ps1
  eng/common/scripts/typespec/New-EmitterPackageLock.ps1
Labels: EngSys, Central-EngSys

#1514 Updated `targetSdkVersion` and `compileSdkVersion`
  build.gradle
  eng/pipelines/templates/variables/globals.yml
  samples/sample-chat-app/build.gradle
  samples/sample-chat-app/src/main/AndroidManifest.xml
  sdk/communication/azure-communication-chat/CHANGELOG.md
  sdk/communication/azure-communication-common/CHANGELOG.md
  sdk/core/azure-core-credential/CHANGELOG.md
  sdk/core/azure-core-credential/README.md
  sdk/core/azure-core-credential/gradle.properties
  sdk/core/azure-core-http-httpurlconnection/CHANGELOG.md
  sdk/core/azure-core-http-httpurlconnection/README.md
  sdk/core/azure-core-http-httpurlconnection/gradle.properties
  sdk/core/azure-core-http-okhttp/CHANGELOG.md
  sdk/core/azure-core-http-okhttp/README.md
  sdk/core/azure-core-http-okhttp/gradle.properties
  sdk/core/azure-core-http/CHANGELOG.md
  sdk/core/azure-core-http/README.md
  sdk/core/azure-core-http/gradle.properties
  sdk/core/azure-core-jackson/CHANGELOG.md
  sdk/core/azure-core-jackson/README.md
  sdk/core/azure-core-jackson/gradle.properties
  sdk/core/azure-core-logging/CHANGELOG.md
  sdk/core/azure-core-logging/README.md
  sdk/core/azure-core-logging/gradle.properties
  sdk/core/azure-core-rest/CHANGELOG.md
  sdk/core/azure-core-rest/README.md
  sdk/core/azure-core-rest/gradle.properties
  sdk/core/azure-core-test/CHANGELOG.md
  sdk/core/azure-core-test/README.md
  sdk/core/azure-core-test/gradle.properties
  sdk/core/azure-core/CHANGELOG.md
  sdk/core/azure-core/README.md
  sdk/core/azure-core/gradle.properties
  sdk/template/azure-sdk-template/gradle.properties
Labels: EngSys, Client

#1518 Sync .github/workflows directory with azure-sdk-tools for PR 7703
  .github/workflows/event-processor.yml
  .github/workflows/scheduled-event-processor.yml
Labels: EngSys, Central-EngSys

#1519 Sync eng/common directory with azure-sdk-tools for PR 7704
  eng/common/pipelines/codeowners-linter.yml
Labels: EngSys, Central-EngSys

#1520 [ANDROID] Communication Common | Microsoft Teams App Identifier feature GA release updates
  sdk/communication/azure-communication-common/CHANGELOG.md
  sdk/communication/azure-communication-common/README.md
Labels: Communication, Communication - Common

#1521 Post release changes for ACS Common releases
  build.gradle
  sdk/communication/azure-communication-common/CHANGELOG.md
  sdk/communication/azure-communication-common/gradle.properties
Labels: Communication, Communication - Common

#1524 Sync .github/workflows directory with azure-sdk-tools for PR 7742
  .github/workflows/event-processor.yml
  .github/workflows/scheduled-event-processor.yml
Labels: EngSys, Central-EngSys

#1523 Prepared new ACS Common release.
  build.gradle
  sdk/communication/azure-communication-common/CHANGELOG.md
  sdk/communication/azure-communication-common/README.md
  sdk/communication/azure-communication-common/gradle.properties
Labels: Client, Communication - Common

#1525 Updated ACS Common CHANGELOG.
  sdk/communication/azure-communication-common/CHANGELOG.md
Labels: Communication - Common

#1528 Sync .github/workflows directory with azure-sdk-tools for PR 7765
  .github/workflows/event-processor.yml
  .github/workflows/scheduled-event-processor.yml
Labels: EngSys, Central-EngSys

#1529 Sync eng/common directory with azure-sdk-tools for PR 7767
  eng/common/pipelines/codeowners-linter.yml
Labels: EngSys, Central-EngSys

#1526 Sync eng/common directory with azure-sdk-tools for PR 7729
  eng/common/scripts/typespec/New-EmitterPackageLock.ps1
Labels: EngSys, Central-EngSys

#1531 Prepare ACS Chat release.
  build.gradle
  sdk/communication/azure-communication-chat/CHANGELOG.md
  sdk/communication/azure-communication-chat/README.md
  sdk/communication/azure-communication-chat/gradle.properties
Labels: Client, Communication - Chat

#1527 Sync eng/common directory with azure-sdk-tools for PR 7682
  eng/common/scripts/job-matrix/job-matrix-functions.ps1
Labels: EngSys, Central-EngSys

#1532 Sync .github/workflows directory with azure-sdk-tools for PR 7796
  .github/workflows/event-processor.yml
  .github/workflows/scheduled-event-processor.yml
Labels: EngSys, Central-EngSys
